<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>textbook-and-reading-recommendations – PHYD57H3: Advanced Computational Methods in Physics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b626d73c4c936ccc3cb08be7d45d1df6.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f6e81f4864cb6d8b696b855696ff1c11.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-86a62c4a56120b95dfa8e5b77e93b73a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-f6e81f4864cb6d8b696b855696ff1c11.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PHYD57H3: Advanced Computational Methods in Physics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes/index.html"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../problems/index.html"> 
<span class="menu-text">Problem Sets</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../simulations/index.html"> 
<span class="menu-text">Code &amp; Simulations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../reference/index.html"> 
<span class="menu-text">Reference &amp; Math</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#you-asked" id="toc-you-asked" class="nav-link active" data-scroll-target="#you-asked">you asked</a></li>
  <li><a href="#gemini-response" id="toc-gemini-response" class="nav-link" data-scroll-target="#gemini-response">gemini response</a>
  <ul class="collapse">
  <li><a href="#website-architecture-and-subpage-resources" id="toc-website-architecture-and-subpage-resources" class="nav-link" data-scroll-target="#website-architecture-and-subpage-resources">1. Website Architecture and Subpage Resources</a></li>
  <li><a href="#full-12-week-course-curriculum" id="toc-full-12-week-course-curriculum" class="nav-link" data-scroll-target="#full-12-week-course-curriculum">2. Full 12-Week Course Curriculum</a></li>
  <li><a href="#computing-architecture-and-toolchains" id="toc-computing-architecture-and-toolchains" class="nav-link" data-scroll-target="#computing-architecture-and-toolchains">3. Computing Architecture and Toolchains</a></li>
  <li><a href="#course-deliverables-and-grading-scheme" id="toc-course-deliverables-and-grading-scheme" class="nav-link" data-scroll-target="#course-deliverables-and-grading-scheme">4. Course Deliverables and Grading Scheme</a></li>
  </ul></li>
  <li><a href="#you-asked-1" id="toc-you-asked-1" class="nav-link" data-scroll-target="#you-asked-1">you asked</a></li>
  <li><a href="#gemini-response-1" id="toc-gemini-response-1" class="nav-link" data-scroll-target="#gemini-response-1">gemini response</a>
  <ul class="collapse">
  <li><a href="#part-1-readings-for-assignment-1-a1" id="toc-part-1-readings-for-assignment-1-a1" class="nav-link" data-scroll-target="#part-1-readings-for-assignment-1-a1">Part 1: Readings for Assignment 1 (A1)</a></li>
  <li><a href="#part-2-readings-for-assignment-2-a2" id="toc-part-2-readings-for-assignment-2-a2" class="nav-link" data-scroll-target="#part-2-readings-for-assignment-2-a2">Part 2: Readings for Assignment 2 (A2)</a></li>
  <li><a href="#part-3-readings-for-the-midterm-exam" id="toc-part-3-readings-for-the-midterm-exam" class="nav-link" data-scroll-target="#part-3-readings-for-the-midterm-exam">Part 3: Readings for the Midterm Exam</a></li>
  <li><a href="#master-reading-checklist-prior-to-midterm" id="toc-master-reading-checklist-prior-to-midterm" class="nav-link" data-scroll-target="#master-reading-checklist-prior-to-midterm">Master Reading Checklist Prior to Midterm</a></li>
  </ul></li>
  <li><a href="#you-asked-2" id="toc-you-asked-2" class="nav-link" data-scroll-target="#you-asked-2">you asked</a></li>
  <li><a href="#gemini-response-2" id="toc-gemini-response-2" class="nav-link" data-scroll-target="#gemini-response-2">gemini response</a>
  <ul class="collapse">
  <li><a href="#phase-1-systems-shells-and-language-toolchains-lectures-13" id="toc-phase-1-systems-shells-and-language-toolchains-lectures-13" class="nav-link" data-scroll-target="#phase-1-systems-shells-and-language-toolchains-lectures-13">Phase 1: Systems, Shells, and Language Toolchains (Lectures 1–3)</a></li>
  <li><a href="#phase-2-material-for-assignment-1-due-lecture-4" id="toc-phase-2-material-for-assignment-1-due-lecture-4" class="nav-link" data-scroll-target="#phase-2-material-for-assignment-1-due-lecture-4">Phase 2: Material for Assignment 1 (Due Lecture 4)</a></li>
  <li><a href="#phase-3-material-for-assignment-2-due-lecture-6" id="toc-phase-3-material-for-assignment-2-due-lecture-6" class="nav-link" data-scroll-target="#phase-3-material-for-assignment-2-due-lecture-6">Phase 3: Material for Assignment 2 (Due Lecture 6)</a></li>
  <li><a href="#phase-4-midterm-exam-preparation-lecture-7" id="toc-phase-4-midterm-exam-preparation-lecture-7" class="nav-link" data-scroll-target="#phase-4-midterm-exam-preparation-lecture-7">Phase 4: Midterm Exam Preparation (Lecture 7)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7"></h1></header><div class="quarto-title-block"><div class="quarto-title-tools-only"><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>





<blockquote class="blockquote">
<p>From: https://gemini.google.com/app/d5fdbfc39d798c48</p>
</blockquote>
<section id="you-asked" class="level1">
<h1>you asked</h1>
<p>message time: 2026-10-03 14:54:40</p>
<p>https://planets.utsc.utoronto.ca/~pawel/PHYD57/</p>
<p>1 Structure and scope of the course Syllabus of PHYD57 Numerical Comp. in Physical Sciences: History and Contemporary efforts</p>
<p>2 HPC: need for speed, why and how History and modernity: microprocessors, Unix, Linux, and Internet Intro to Linux (CentOS) Command line interface and shells (bash and tcsh) Text editors: vi, nano, gedit, micro</p>
<p>3 Connectivity (ssh &amp; sftp, traceroute &amp; ping) Securing the linux system against break-ins via /etc/hosts.deny Basic Linux shells and commands (bash, tcsh, cd, ls, ps, cd, &amp;, bg, fg, alias, export/setenv, rm, output redirection to file via &gt;) Getting more info: manual pages (man), -h, –help, or -help modifiers Recommended compilers: GNU: gcc, gfortran; Intel: icc, ifort or ifx; Nvidia: nvcc/nvc++, nvfortran (formerly pgf95) Simple program in C, Fortran95, Python, Matlab, IDL (Schoerghofer,p.30) More complex program, example of HPC: 2nd order Laplace operator stencil for the diffusion equation Speed comparison of C/F95 with Python &amp; Numpy: why we learn HPC</p>
<p>4 C and Fortran 95 - compilers, basic usage<br>
Numerical puzzle of 711 - learning C and Fortran Kruskal counts and their connection to linked lists Coding Kruskal counts trick in Python and Fortran C: Language overview, compilers Integration with Python: calling C from Python Examples of programs</p>
<p>5 Dicussion of the solutions of A2 assignment set More Fortran. Monte Carlo method (MtC) Examples of programs: Random numbers and MtC (finding π) Slow convergence: const./sqrt(N) scaling of error in MtC Parallel execution on CPU using OpenMP fork-join method in loops Parallel implementations: in-depth diffusion equation</p>
<p>6 Modern computing in the era of Integrated Circuits 2000s: Appearence of barriers to single-thread computing The only solution: parallelism Moore’s law: sustainable or not? also look at the website in details, its subpages etc.</p>
<hr>
</section>
<section id="gemini-response" class="level1">
<h1>gemini response</h1>
<p>The course portal for <strong>PHYD57 (Advanced Computational Methods in Physics)</strong> hosted at <code>planets.utsc.utoronto.ca/~pawel/PHYD57/</code> serves as the primary centralized hub for lecture syllabi, computing cluster access rules, reading references, and project descriptions curated by Prof.&nbsp;Pawel Artymowicz.</p>
<hr>
<section id="website-architecture-and-subpage-resources" class="level3">
<h3 class="anchored" data-anchor-id="website-architecture-and-subpage-resources">1. Website Architecture and Subpage Resources</h3>
<p>The course site operates as an unstyled, direct academic directory containing links to syllabi, project documentation, external texts, and hidden resource pages:</p>
<ul>
<li><strong>Central Course Hub (<code>/PHYD57/</code>):</strong> Contains the official syllabus text file, lecture schedule, language policies, assignment submission criteria, and midterm/final examination rules.</li>
<li><strong>PHYD57 References Page (<code>References</code> subpage):</strong> Hosts recommended readings and technical PDFs covering core languages and computing history:
<ul>
<li><em>Lessons in Scientific Computing</em> by Norbert Schörghofer (specifically pages 25–35 detailing runtime benchmarks between C, Modern Fortran, and Python).</li>
<li><em>Computational Quantum Mechanics</em> by J. Izaac and J. B. Wang (Chapter 2 for Modern Fortran syntax and Chapter 3 for scientific Python).</li>
<li><em>The Definitive Guide to CentOS</em> by Membrey (Chapter 3, covering headless server setups and remote access).</li>
<li><em>A History of Modern Computing</em> by Paul E. Ceruzzi.</li>
<li><em>Programming for Computations – Python</em> by Svein Linge and Aslak Tveito.</li>
</ul></li>
<li><strong>Project Dossiers and Hidden Subdirectories:</strong>
<ul>
<li><strong>Aerodynamics &amp; Flight Dynamics (<code>/~pawel/s/</code>):</strong> A hidden directory (accessed by replacing <code>PHYD57</code> with <code>s</code> in the URL) dedicated to the Smolensk Tu-154 crash aerodynamic reconstruction, Prandtl lifting-line theory, and 3D vortex panel methods.</li>
<li><strong>Smoothed Particle Hydrodynamics (SPH):</strong> Papers by J. J. Monaghan (1997, 2005) and Stephan Rosswog (<em>Astrophysical SPH</em>) covering Lagrangian fluid modeling.</li>
<li><strong>N-Body and Galactic Dynamics:</strong> Dynamics references based on Binney &amp; Tremaine’s <em>Galactic Dynamics</em>, alongside CUDA N-body integration engines.</li>
<li><strong>Fast Fourier Transforms (FFT):</strong> Reference texts by E. Oran Brigham and NVIDIA’s <code>CUFFT_Library.pdf</code> documentation for solving Poisson and gravitational potential convolutions in <span class="math inline">\(\mathcal{O}(N \ln N)\)</span> time.</li>
<li><strong>Structural Mechanics (Golden Gate Project):</strong> Suspension bridge modeling based on Gimsing (<em>Cable Supported Bridges</em>) and Gazzola (<em>Mathematical Models for Suspension Bridges</em>).</li>
</ul></li>
</ul>
<hr>
</section>
<section id="full-12-week-course-curriculum" class="level3">
<h3 class="anchored" data-anchor-id="full-12-week-course-curriculum">2. Full 12-Week Course Curriculum</h3>
<p>The lecture and tutorial track advances from POSIX command-line mechanics to multi-core threading and massively parallel GPU acceleration:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Week</th>
<th style="text-align: left;">Lecture Topics</th>
<th style="text-align: left;">Practical &amp; Computational Focus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1</strong></td>
<td style="text-align: left;">Course Scope &amp; History of Numerical Computing</td>
<td style="text-align: left;">Overview of physical simulation paradigms and course logistics.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>2</strong></td>
<td style="text-align: left;">Microprocessor Evolution &amp; Unix/Linux Essentials</td>
<td style="text-align: left;">CentOS environment, bash/tcsh shells, and terminal text editors (<code>vi</code>, <code>nano</code>, <code>gedit</code>, <code>micro</code>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>3</strong></td>
<td style="text-align: left;">Networking &amp; Low-Level Language Benchmarking</td>
<td style="text-align: left;">SSH/SFTP, <code>/etc/hosts.deny</code> security, GNU/Intel/NVIDIA compiler toolchains, 2nd-order Laplace diffusion stencils, and C/Fortran vs.&nbsp;Python/NumPy execution speed comparisons.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>4</strong></td>
<td style="text-align: left;">C &amp; Modern Fortran 95 Implementations</td>
<td style="text-align: left;">Compiler optimization flags, the Numerical Puzzle of 711, Kruskal counts, linked list mechanics, and calling C routines from Python.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>5</strong></td>
<td style="text-align: left;">Monte Carlo Integration &amp; Early OpenMP</td>
<td style="text-align: left;">Pseudo-random number generators, calculating <span class="math inline">\(\pi\)</span>, <span class="math inline">\(\mathcal{O}(N^{-1/2})\)</span> statistical error convergence, OpenMP fork-join loops, and parallelizing the 2D heat diffusion equation.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>6</strong></td>
<td style="text-align: left;">Integrated Circuit Scaling &amp; Hardware Limits</td>
<td style="text-align: left;">Dennard scaling breakdown, single-thread performance walls, multi-core chip architectures, and the sustainability of Moore’s Law.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>7</strong></td>
<td style="text-align: left;">Many-Core Architectures &amp; Memory Models</td>
<td style="text-align: left;">Introduction to group project (A4) options, Intel Many Integrated Core (MIC / Xeon Phi), supercomputing clusters, and row-major (C) vs.&nbsp;column-major (Fortran) array ordering.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>8</strong></td>
<td style="text-align: left;">Advanced OpenMP &amp; Single-Node Bottlenecks</td>
<td style="text-align: left;">Stack overflow segmentation faults, CPU compute vs.&nbsp;RAM bandwidth constraints, DISLIN graphics library, wave equations, linked-list neighbor searches, and SPH implementations.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>9</strong></td>
<td style="text-align: left;">Vectorization, MIC &amp; Introduction to CUDA</td>
<td style="text-align: left;">Compiler auto-vectorization reports, optically thick disk radiation (IRI), N-body gravitational integration, and simple neural net stabilization (inverted pendulum problem).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>10</strong></td>
<td style="text-align: left;">Astrophysical Disks, Hydrodynamics &amp; FFT</td>
<td style="text-align: left;">Protoplanetary disk simulations, Eulerian vs.&nbsp;Lagrangian fluids (<code>fluidsGL</code>), gravitational potentials via FFT convolutions, zero-padding/aliasing, and CUDA Fortran kernels.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>11</strong></td>
<td style="text-align: left;">Massively Parallel CUDA &amp; Machine Learning</td>
<td style="text-align: left;">CUDA C/C++ thread hierarchies, tetrahedrons puzzle, intro to MPI, neural network dimensionality, overfitting, and the Nelder–Mead Simplex optimization algorithm.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>12</strong></td>
<td style="text-align: left;">Research Project Capstone</td>
<td style="text-align: left;">In-class presentations and evaluations of student A4 group research projects.</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="computing-architecture-and-toolchains" class="level3">
<h3 class="anchored" data-anchor-id="computing-architecture-and-toolchains">3. Computing Architecture and Toolchains</h3>
<p>The course centers on direct access to departmental research clusters housed in the Science Wing and BV Building at UTSC:</p>
<ul>
<li><strong>Cluster Environments:</strong>
<ul>
<li><code>art-1</code> and <code>art-2</code>: Multi-core servers running CentOS 6 with <code>tcsh</code> as the default shell. Users authenticate over legacy SSH ciphers (<code>-o HostKeyAlgorithms=+ssh-dss</code>).</li>
<li><code>art-16</code>: Modern GPU accelerator nodes running Rocky Linux 9 with modern <code>bash</code>.</li>
<li><code>phi</code>: Multi-core compute nodes equipped with Intel Xeon Phi (Many Integrated Core / MIC) co-processors.</li>
</ul></li>
<li><strong>Compiler Suites:</strong>
<ul>
<li><strong>GNU Compiler Collection (GCC):</strong> <code>gcc</code>, <code>g++</code>, and <code>gfortran</code>.</li>
<li><strong>NVIDIA HPC SDK:</strong> <code>nvcc</code>, <code>nvc</code>, <code>nvc++</code>, and <code>nvfortran</code> (modern replacement for PGI <code>pgf90</code>/<code>pgf95</code>).</li>
<li><strong>Intel oneAPI:</strong> <code>icx</code>, <code>icpx</code>, and <code>ifx</code> (modern replacement for legacy <code>icc</code> and <code>ifort</code>).</li>
</ul></li>
<li><strong>Language Policy:</strong>
<ul>
<li><em>Passive Requirement:</em> Mandatory ability to read, trace, and debug both C and Modern Fortran (90/95/2003/2008) in lecture codes and exams.</li>
<li><em>Active Requirement:</em> Students select either C/C++ or Modern Fortran as their primary language for homework and exams.</li>
<li><em>Python:</em> Restricted to an auxiliary role (prototyping, driver scripts, plotting data with Matplotlib, and testing numerical accuracy) rather than writing inner simulation kernels.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="course-deliverables-and-grading-scheme" class="level3">
<h3 class="anchored" data-anchor-id="course-deliverables-and-grading-scheme">4. Course Deliverables and Grading Scheme</h3>
<p>Term evaluations balance numerical physics problem sets, multi-threaded coding assignments, and in-person exams:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Deliverable</th>
<th style="text-align: left;">Weight</th>
<th style="text-align: left;">Key Deadlines &amp; Structural Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Assignment 1 (A1)</strong></td>
<td style="text-align: left;"><strong>7%</strong></td>
<td style="text-align: left;">Due at 11:00 AM on Lecture 4. Covers flight mechanics, air-water ballistics, <span class="math inline">\(\mathcal{O}(N)\)</span> optimization, and 2nd-derivative stencil truncation error.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Assignment 2 (A2)</strong></td>
<td style="text-align: left;"><strong>7%</strong></td>
<td style="text-align: left;">Due at 11:00 AM on Lecture 6. Centers on Monte Carlo simulations, convergence rates, and initial OpenMP loop parallelization.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Midterm Exam</strong></td>
<td style="text-align: left;"><strong>16%</strong></td>
<td style="text-align: left;">Held in-class during Lecture 7 (11:10–12:10 AM). Split evenly: 8% written problem solving and 8% theoretical quiz.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Assignment 3 (A3)</strong></td>
<td style="text-align: left;"><strong>7%</strong></td>
<td style="text-align: left;">Due at 11:00 AM on Lecture 10. Focuses on advanced OpenMP, FFT convolutions, and initial CUDA GPU kernel development.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Group Project (A4)</strong></td>
<td style="text-align: left;"><strong>23%</strong></td>
<td style="text-align: left;">Groups finalized by Lecture 6; project presentations during Lecture 12. Involves developing an end-to-end HPC simulation (SPH fluids, N-body dynamics, aerodynamics, or bridge oscillations).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Final Exam</strong></td>
<td style="text-align: left;"><strong>40%</strong></td>
<td style="text-align: left;">In-person 3-hour examination split into two sections: ~1.5 hours closed-book written theory and quiz, followed by ~1.5 hours of live coding on a personal laptop or via remote SSH to the <code>art</code> cluster. Students may bring up to 8 handwritten note pages (4 double-sided sheets).</td>
</tr>
</tbody>
</table>
<p><em>Submission Policy:</em> Work submitted more than 3 hours past the 11:00 AM deadline receives an automatic 50% deduction, with no extensions granted due to in-class solution discussions during tutorials. Academic illness accommodations require an official Verification of Illness (VOI) form or ACORN self-declaration.</p>
<hr>
</section>
</section>
<section id="you-asked-1" class="level1">
<h1>you asked</h1>
<p>message time: 2026-10-03 14:56:57</p>
<p>what chapters/sectiosn i need to read from suggested or other soruces textbooks or onlie to prepare for midterm, and cover material needed to get a1, a2 assignmetns done</p>
<hr>
</section>
<section id="gemini-response-1" class="level1">
<h1>gemini response</h1>
<p>To successfully complete <strong>Assignment 1 (A1)</strong>, <strong>Assignment 2 (A2)</strong>, and pass both the written problem-solving and theoretical quiz portions of the <strong>Midterm Exam</strong> (Lectures 1–6), your reading must cover three integrated areas: <strong>analytical and numerical physics modeling</strong>, <strong>low-level systems and memory architectures (C &amp; Modern Fortran)</strong>, and <strong>parallel execution (OpenMP)</strong>.</p>
<hr>
<section id="part-1-readings-for-assignment-1-a1" class="level3">
<h3 class="anchored" data-anchor-id="part-1-readings-for-assignment-1-a1">Part 1: Readings for Assignment 1 (A1)</h3>
<p><em>Due Lecture 4; covers flight dynamics, multiphase ballistics, algorithmic complexity, and finite-difference error scaling.</em></p>
<section id="problem-1.1-f-16-aerobatic-loop-analysis" class="level4">
<h4 class="anchored" data-anchor-id="problem-1.1-f-16-aerobatic-loop-analysis">Problem 1.1: F-16 Aerobatic Loop Analysis</h4>
<ul>
<li><strong>John D. Anderson — <em>Introduction to Flight</em> (8th/9th Ed.)</strong>
<ul>
<li><strong>Chapter 5 (§5.13–§5.15): Accelerated Flight &amp; Pull-up Maneuvers:</strong> Derives normal load factor <span class="math inline">\(n = 1 + v^2/(gR)\)</span>, centripetal pull-up force balance, and apex weightlessness yielding the circular radius relation <span class="math inline">\(R = v_0^2/(5g)\)</span>.</li>
<li><strong>Chapter 5 (§5.16): The <span class="math inline">\(V\text{–}n\)</span> Flight Envelope:</strong> Explains structural load limits and dynamic stall speed scaling <span class="math inline">\(v_S(n) = v_{S,0}\sqrt{n}\)</span>.</li>
</ul></li>
<li><strong>Bernard Etkin &amp; Lloyd Duff Reid — <em>Dynamics of Flight: Stability and Control</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 5 (§5.1–§5.6): Vertical-Plane Trajectory Dynamics:</strong> Formulates the coupled longitudinal equations of motion in speed <span class="math inline">\(v(t)\)</span> and flight-path angle <span class="math inline">\(\theta(t)\)</span> under quadratic drag and load-dependent induced drag (<span class="math inline">\(C_D = C_{D0} + K C_L^2\)</span>).</li>
</ul></li>
<li><strong>William H. Press et al.&nbsp;— <em>Numerical Recipes: The Art of Scientific Computing</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 16 (§16.1–§16.3): Runge–Kutta &amp; Adaptive Step-Size Control:</strong> Explains how to integrate non-linear coupled ODEs with explicit loop closure checks at <span class="math inline">\(\theta = 2\pi\)</span>.</li>
</ul></li>
<li><strong>Robert Resnick, David Halliday, &amp; Kenneth S. Krane — <em>Physics, Vol. 1</em> (5th Ed.)</strong>
<ul>
<li><strong>Chapter 4 (§4.5) &amp; Chapters 7–8:</strong> Airspeed vector triangles under wind shear and mechanical work-energy conservation (<span class="math inline">\(v(y) = \sqrt{v_0^2 - 2gy}\)</span>).</li>
</ul></li>
<li><strong>Vladimir Arnold — <em>Mathematical Methods of Classical Mechanics</em> (2nd Ed.)</strong> <em>(Advanced/Trans-Syllabus)</em>
<ul>
<li><strong>Chapter 3 (§12, §16):</strong> Clothoid (Euler spiral) curvature parameterization (<span class="math inline">\(\kappa(s) = s/A^2\)</span>) to eliminate unbounded normal jerk (<span class="math inline">\(\dot{n} \to \infty\)</span>).</li>
</ul></li>
</ul>
</section>
<section id="problem-1.2-multiphase-air-water-ballistics" class="level4">
<h4 class="anchored" data-anchor-id="problem-1.2-multiphase-air-water-ballistics">Problem 1.2: Multiphase Air-Water Ballistics</h4>
<ul>
<li><strong>John R. Taylor — <em>Classical Mechanics</em></strong>
<ul>
<li><strong>Chapter 2 (§2.1–§2.4): Motion in Resisting Media:</strong> Formulates 1D/2D quadratic aerodynamic drag (<span class="math inline">\(\mathbf{F}_D = -\frac{1}{2}\rho C_D A v \mathbf{v}\)</span>) and closed-form vertical terminal velocity <span class="math inline">\(v_t = \sqrt{2m g_{\text{eff}} / (\rho C_D A)}\)</span>.</li>
</ul></li>
<li><strong>Resnick, Halliday, &amp; Krane — <em>Physics, Vol. 1</em> (5th Ed.)</strong>
<ul>
<li><strong>Chapter 15 (§15.1–§15.4): Fluid Statics &amp; Buoyancy:</strong> Derives Archimedes’ principle and effective gravitational acceleration in water: <span class="math inline">\(g_{\text{eff}} = g(1 - \rho_w/\rho_p)\)</span>.</li>
</ul></li>
<li><strong>Randall J. LeVeque — <em>Finite Difference Methods for Ordinary and Partial Differential Equations</em></strong>
<ul>
<li><strong>Chapters 1–3: Initial Value Problems &amp; Discontinuous Interfaces:</strong> Staggered time-stepping across discontinuous media boundaries (the <span class="math inline">\(\sim 800\times\)</span> density jump at <span class="math inline">\(y=0\)</span>).</li>
</ul></li>
<li><strong>Press et al.&nbsp;— <em>Numerical Recipes</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 9 &amp; Chapter 16 (§16.6): Root Finding &amp; Stiff Systems:</strong> Brent’s method for zero-crossing detection to pinpoint the air-water impact time <span class="math inline">\(t^*\)</span> without step-overs, along with handling stiff deceleration spikes.</li>
</ul></li>
</ul>
</section>
<section id="problem-1.3-vector-monotonicity-subsegment-growth" class="level4">
<h4 class="anchored" data-anchor-id="problem-1.3-vector-monotonicity-subsegment-growth">Problem 1.3: Vector Monotonicity &amp; Subsegment Growth</h4>
<ul>
<li><strong>Thomas H. Cormen et al.&nbsp;(CLRS) — <em>Introduction to Algorithms</em> (3rd/4th Ed.)</strong>
<ul>
<li><strong>Chapter 3 (§3.1–§3.2) &amp; Chapter 4 (§4.1): Asymptotic Growth &amp; Maximum Subarray:</strong> Formal algebraic proofs comparing naive pairwise <span class="math inline">\(\sum_{i=1}^{N-1}(N-i) = \frac{N(N-1)}{2} \in \Theta(N^2)\)</span> against single-pass <span class="math inline">\(\Theta(N)\)</span> running-minimum scans with <span class="math inline">\(\mathcal{O}(1)\)</span> storage.</li>
</ul></li>
<li><strong>Randal E. Bryant &amp; David R. O’Hallaron — <em>Computer Systems: A Programmer’s Perspective (CS:APP)</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 5: Optimizing Program Performance:</strong> Instruction-level parallelism (ILP), unrolling loops, branch predictability, and eliminating memory stalls.</li>
<li><strong>Chapter 6: The Memory Hierarchy:</strong> 64-byte L1/L2/L3 cache lines, spatial/temporal locality, and avoiding strided cache thrashing during multi-million-element traversals.</li>
</ul></li>
</ul>
</section>
<section id="problem-1.4-second-derivative-stencil-limits" class="level4">
<h4 class="anchored" data-anchor-id="problem-1.4-second-derivative-stencil-limits">Problem 1.4: Second-Derivative Stencil Limits</h4>
<ul>
<li><strong>Randall J. LeVeque — <em>Finite Difference Methods for Ordinary and Partial Differential Equations</em></strong>
<ul>
<li><strong>Chapter 1 (§1.1–§1.3): Truncation Error &amp; Taylor Series:</strong> Deriving the second-order truncation error bound (<span class="math inline">\(E_{\text{trunc}} = \frac{h^2}{12}|f^{(4)}(\xi)|\)</span>) for the 3-point central difference stencil.</li>
</ul></li>
<li><strong>Mark Newman — <em>Computational Physics</em></strong>
<ul>
<li><strong>Chapter 5 (§5.10): Numerical Derivatives &amp; Roundoff Error:</strong> Analytical derivation of catastrophic subtractive cancellation (<span class="math inline">\(E_{\text{round}} = 4\epsilon_{\text{mach}}|f| / h^2\)</span>), proving the optimal step size minimizes at <span class="math inline">\(h_{\text{opt}} \sim \epsilon_{\text{mach}}^{1/4}\)</span>, and plotting the log-log error V-curve.</li>
</ul></li>
<li><strong>Schörghofer — <em>Lessons in Scientific Computing</em> (CRC 2019)</strong>
<ul>
<li><strong>Chapter 1 (pp.&nbsp;25–35):</strong> Benchmarking compiled C/Fortran stencils against Python/NumPy.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="part-2-readings-for-assignment-2-a2" class="level3">
<h3 class="anchored" data-anchor-id="part-2-readings-for-assignment-2-a2">Part 2: Readings for Assignment 2 (A2)</h3>
<p><em>Due Lecture 6; covers Monte Carlo methods, PRNGs, <span class="math inline">\(1/\sqrt{N}\)</span> error convergence, and OpenMP multi-threading.</em></p>
<section id="monte-carlo-integration-random-number-generation" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-integration-random-number-generation">Monte Carlo Integration &amp; Random Number Generation</h4>
<ul>
<li><strong>Mark Newman — <em>Computational Physics</em></strong>
<ul>
<li><strong>Chapter 10 (§10.1–§10.3): Random Numbers &amp; Monte Carlo Integration:</strong>
<ul>
<li><em>§10.1:</em> Linear congruential generators (LCGs), pseudo-random sequences, seeds, and uniform distribution sampling.</li>
<li><em>§10.2:</em> Monte Carlo evaluation of definite integrals (e.g., finding <span class="math inline">\(\pi\)</span> via circle-in-a-square hit-or-miss and mean-value integration).</li>
<li><em>§10.3:</em> Statistical errors and the Central Limit Theorem: rigorous proof of the slow <span class="math inline">\(\sigma \propto \frac{1}{\sqrt{N}}\)</span> error scaling law independent of spatial dimensionality.</li>
</ul></li>
</ul></li>
<li><strong>Press et al.&nbsp;— <em>Numerical Recipes</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 7 (§7.1–§7.3): Random Numbers:</strong> Uniform random deviates, period lengths, avoiding defective LCG artifacts (Marsaglia planes).</li>
<li><strong>Chapter 15 (§15.1): Modeling of Data:</strong> Statistical variance, sample standard deviations, and confidence intervals for stochastic physical simulations.</li>
</ul></li>
</ul>
</section>
<section id="openmp-loop-parallelization-2d-diffusion" class="level4">
<h4 class="anchored" data-anchor-id="openmp-loop-parallelization-2d-diffusion">OpenMP Loop Parallelization &amp; 2D Diffusion</h4>
<ul>
<li><strong>Georg Hager &amp; Gerhard Wellein — <em>Introduction to High Performance Computing for Scientists and Engineers</em></strong>
<ul>
<li><strong>Chapter 6: Shared-Memory Parallel Programming with OpenMP:</strong>
<ul>
<li><em>§6.1–§6.2:</em> The fork-join thread execution model, parallel regions, and work-sharing loops (<code>#pragma omp parallel for</code> in C, <code>!$omp parallel do</code> in Fortran).</li>
<li><em>§6.3:</em> Data scoping rules: distinguishing <code>shared</code> memory arrays from loop-private variables (<code>private</code>, <code>firstprivate</code>), thread safety, and preventing data races.</li>
<li><em>§6.4:</em> Reduction clauses (<code>reduction(+:sum)</code>): how multi-threaded Monte Carlo loops accumulate partial sums across cores without mutex lock contention.</li>
</ul></li>
</ul></li>
<li><strong>Milan Curcic — <em>Modern Fortran: Building Efficient Parallel Applications</em></strong>
<ul>
<li><strong>Chapter 11 &amp; 12: Parallelism with OpenMP &amp; Hardware Vectors:</strong> Implementing OpenMP directives over multidimensional Fortran arrays and understanding loop chunk scheduling (<code>schedule(static)</code> vs <code>schedule(dynamic)</code>).</li>
</ul></li>
<li><strong>LeVeque — <em>Finite Difference Methods</em></strong>
<ul>
<li><strong>Chapter 9: Diffusion Equations &amp; Parabolic PDEs:</strong> Setting up the explicit 2D 5-point Laplace stencil: <span class="math display">\[u_{i,j}^{n+1} = u_{i,j}^n + \Delta t \left( \frac{u_{i+1,j}^n - 2u_{i,j}^n + u_{i-1,j}^n}{\Delta x^2} + \frac{u_{i,j+1}^n - 2u_{i,j}^n + u_{i,j-1}^n}{\Delta y^2} \right)\]</span> Parallelizing grid update loops with OpenMP, managing inner vs.&nbsp;boundary points, and verifying the CFL stability criterion (<span class="math inline">\(\Delta t \le \frac{\Delta x^2}{4D}\)</span>).</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="part-3-readings-for-the-midterm-exam" class="level3">
<h3 class="anchored" data-anchor-id="part-3-readings-for-the-midterm-exam">Part 3: Readings for the Midterm Exam</h3>
<p><em>Held in Lecture 7; 16% of total grade (8% written problem solving + 8% multiple-choice/fill-in-the-blank quiz). Allowed aid: 8 handwritten note pages (4 double-sided sheets) and a calculator.</em></p>
<section id="a.-microprocessor-history-hardware-architecture-physical-limits-quiz-scope" class="level4">
<h4 class="anchored" data-anchor-id="a.-microprocessor-history-hardware-architecture-physical-limits-quiz-scope">A. Microprocessor History, Hardware Architecture &amp; Physical Limits (Quiz Scope)</h4>
<ul>
<li><strong>Paul E. Ceruzzi — <em>A History of Modern Computing</em> (2nd Ed.)</strong>
<ul>
<li><strong>Chapters 5 &amp; 6:</strong> Transition from mainframes to microprocessors, Intel x86 architecture evolution, Unix/Linux origins, and the rise of the Internet.</li>
</ul></li>
<li><strong>Hager &amp; Wellein — <em>Introduction to High Performance Computing</em></strong>
<ul>
<li><strong>Chapter 1: Modern Processors:</strong> Pipelining, superscalar execution, clock frequency limits, and SIMD registers.</li>
<li><strong>Chapter 2 (§2.1–§2.3): Memory Hierarchies &amp; Bottlenecks:</strong> Memory wall, arithmetic intensity (FLOPs per byte of DRAM transfer), and L1/L2/L3 cache latency vs.&nbsp;main memory bandwidth.</li>
<li><strong>Chapter 3: Parallel Computers:</strong> Dennard scaling breakdown (leakage currents and the thermal “power wall” around 2004–2005), multi-core CPUs as the only path forward, and the operational meaning of Moore’s Law (transistor count scaling vs.&nbsp;single-thread frequency stagnation).</li>
</ul></li>
</ul>
</section>
<section id="b.-linux-cli-networking-system-security-quiz-scope" class="level4">
<h4 class="anchored" data-anchor-id="b.-linux-cli-networking-system-security-quiz-scope">B. Linux CLI, Networking &amp; System Security (Quiz Scope)</h4>
<ul>
<li><strong>Scott Membrey — <em>The Definitive Guide to CentOS</em></strong>
<ul>
<li><strong>Chapter 3: Working with the Shell &amp; Remote Systems:</strong>
<ul>
<li>Bash vs.&nbsp;tcsh shell environments, environment variables (<code>export</code> vs.&nbsp;<code>setenv</code>), aliases, process management (<code>ps</code>, <code>&amp;</code>, <code>bg</code>, <code>fg</code>, <code>kill</code>), and stream redirection (<code>&gt;</code>, <code>&gt;&gt;</code>, <code>|</code>).</li>
<li>Remote connectivity tools: <code>ssh</code> and <code>sftp</code> port mechanics, <code>ping</code>, <code>traceroute</code>, and MTU limits.</li>
<li>Security mechanisms: Securing access through <code>/etc/hosts.deny</code> and <code>/etc/hosts.allow</code> TCP wrappers.</li>
<li>Text editor fluency: Command modes in <code>vi</code>, basic usage of <code>nano</code> and <code>micro</code>.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="c.-language-mechanics-memory-models-compiler-suites-quiz-written-scope" class="level4">
<h4 class="anchored" data-anchor-id="c.-language-mechanics-memory-models-compiler-suites-quiz-written-scope">C. Language Mechanics, Memory Models &amp; Compiler Suites (Quiz &amp; Written Scope)</h4>
<ul>
<li><strong>Norbert Schörghofer — <em>Lessons in Scientific Computing</em></strong>
<ul>
<li><strong>Chapter 1 (§1.1–§1.4, pp.&nbsp;1–35): Languages &amp; Computational Trade-offs:</strong> Language performance taxonomy (C, Fortran 95, Python, NumPy, MATLAB, IDL); how interpreted dynamic typing incurs massive loop interpretation penalties compared to compiled binaries.</li>
</ul></li>
<li><strong>J. Izaac &amp; J. B. Wang — <em>Computational Quantum Mechanics</em></strong>
<ul>
<li><strong>Chapter 2 (pp.&nbsp;35–75): Modern Fortran Foundations:</strong> Module design, strict typing (<code>implicit none</code>), array slices (<code>A(1:N:2)</code>), dynamic allocation (<code>allocate</code>/<code>deallocate</code>), and intrinsic math functions.</li>
<li><strong>Chapter 3 (pp.&nbsp;77–110): Scientific Python:</strong> NumPy vectorized arrays, SciPy libraries, and calling compiled C/Fortran libraries via Python wrappers (<code>ctypes</code>, <code>f2py</code>).</li>
</ul></li>
<li><strong>K. N. King — <em>C Programming: A Modern Approach</em> (2nd Ed.)</strong>
<ul>
<li><strong>Chapters 11, 12, &amp; 17: Pointers, Arrays, and Dynamic Memory:</strong>
<ul>
<li>Pointer arithmetic and array memory layout: C row-major (lexicographical) order versus Fortran column-major order.</li>
<li>1D flattened contiguous buffers (<code>grid[i * N + j]</code>) versus jagged pointer arrays (<code>grid[i][j]</code>), and why jagged arrays destroy cache locality.</li>
</ul></li>
</ul></li>
<li><strong>Compiler Manuals &amp; Optimization Flags (GCC, Intel, NVIDIA SDK):</strong>
<ul>
<li>GNU (<code>gcc</code>, <code>gfortran</code>), Intel (<code>icc</code>, <code>ifort</code>, <code>ifx</code>), and NVIDIA (<code>nvcc</code>, <code>nvfortran</code> / formerly PGI <code>pgf95</code>).</li>
<li>Optimization flags: <code>-O2</code>, <code>-O3</code>, <code>-march=native</code>, loop unrolling, and <code>-fopenmp</code> / <code>-qopenmp</code>.</li>
</ul></li>
</ul>
</section>
<section id="d.-algorithmic-puzzles-problem-solving-written-quiz-scope" class="level4">
<h4 class="anchored" data-anchor-id="d.-algorithmic-puzzles-problem-solving-written-quiz-scope">D. Algorithmic Puzzles &amp; Problem-Solving (Written &amp; Quiz Scope)</h4>
<ul>
<li><strong>The Numerical Puzzle of 711 (Lecture 4):</strong>
<ul>
<li><em>Concept:</em> Four items whose sum is <span class="math inline">\(\$7.11\)</span> and product is <span class="math inline">\(\$7.11\)</span> (in cents: <span class="math inline">\(a+b+c+d=711\)</span> and <span class="math inline">\(a \cdot b \cdot c \cdot d = 711,000,000\)</span>).</li>
<li><em>Focus:</em> Prime factorization of <span class="math inline">\(711 \times 10^6 = 2^6 \cdot 3^2 \cdot 5^6 \cdot 79\)</span>. Understand analytical constraint pruning (isolating multiples of 79, ordering <span class="math inline">\(a \le b \le c \le d\)</span>) to turn a brute-force <span class="math inline">\(711^4 \approx 2.5 \times 10^{11}\)</span> loop into an efficient multi-loop running in milliseconds in C/Fortran.</li>
</ul></li>
<li><strong>Kruskal Counts &amp; Linked Lists (Lecture 4):</strong>
<ul>
<li><em>Concept:</em> Coupling card-counting permutations and word hops into linked-list node chains. Review pointer references in C and indexed target jumping in Fortran.</li>
</ul></li>
<li><strong>Past Midterm Archive &amp; Course Codes:</strong>
<ul>
<li><strong><code>mid-prep-2026.html</code> and 2025 Midterm Exam Solutions:</strong> Carefully inspect past quiz traps (such as identifying incorrect technical terms inside quadruple asterisks <code>****word****</code>).</li>
<li><strong><code>[http://planets.utsc.utoronto.ca/~pawel/progD57](http://planets.utsc.utoronto.ca/~pawel/progD57)</code>:</strong> Run, inspect, and benchmark the professor’s codes for the 711 puzzle, Kruskal counts, 2D diffusion OpenMP stencils, and Monte Carlo <span class="math inline">\(\pi\)</span> estimation.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="master-reading-checklist-prior-to-midterm" class="level3">
<h3 class="anchored" data-anchor-id="master-reading-checklist-prior-to-midterm">Master Reading Checklist Prior to Midterm</h3>
<pre><code>Pre-Midterm Reading Schedule:
├── Week 1–2 (Linux, Compilers &amp; Languages)
│   ├── Membrey: Ch 3 (CentOS, shells, ssh, /etc/hosts.deny)
│   ├── Schörghofer: Ch 1 (pp. 1–35, language comparison)
│   └── Izaac &amp; Wang: Ch 2 &amp; 3 (Fortran 95 &amp; Python C-bindings)
├── Week 3–4 (A1 Preparation: Dynamics, Stencils, Algorithms)
│   ├── Anderson: Ch 5 (§5.13–§5.16, loop dynamics &amp; stall)
│   ├── Taylor: Ch 2 (§2.1–§2.4, quadratic drag &amp; terminal velocity)
│   ├── CLRS: Ch 3 &amp; 4 (asymptotic proofs for monotonicity scan)
│   ├── Bryant &amp; O'Hallaron: Ch 5 &amp; 6 (cache lines &amp; spatial locality)
│   └── LeVeque: Ch 1 &amp; Newman: Ch 5 (stencil truncation &amp; roundoff envelope)
├── Week 5–6 (A2 Preparation: Monte Carlo &amp; OpenMP)
│   ├── Newman: Ch 10 (random numbers, LCGs, 1/√N error scaling)
│   ├── Hager &amp; Wellein: Ch 6 (OpenMP fork-join, shared/private, reductions)
│   └── LeVeque: Ch 9 (2D diffusion stencils &amp; CFL stability limits)
└── Week 6–7 (Midterm Quiz &amp; Problem Review)
    ├── Hager &amp; Wellein: Ch 1–3 (Dennard scaling, power wall, memory wall)
    ├── King: Ch 11, 12, 17 (C pointers vs. Fortran column-major memory)
    └── Course Archives: mid-prep-2026.html + 2025 Midterm solutions + progD57</code></pre>
<hr>
</section>
</section>
<section id="you-asked-2" class="level1">
<h1>you asked</h1>
<p>message time: 2026-10-03 15:05:56</p>
<p>now jsut give me what to read and in what order to read it</p>
<hr>
</section>
<section id="gemini-response-2" class="level1">
<h1>gemini response</h1>
<section id="phase-1-systems-shells-and-language-toolchains-lectures-13" class="level3">
<h3 class="anchored" data-anchor-id="phase-1-systems-shells-and-language-toolchains-lectures-13">Phase 1: Systems, Shells, and Language Toolchains (Lectures 1–3)</h3>
<p>Read these foundational texts first to navigate the cluster environments (<code>art-1</code> running CentOS with <code>tcsh</code> and <code>art-16</code> running Rocky Linux with <code>bash</code>), configure remote access, and establish baseline C or Modern Fortran compilation pipelines:</p>
<ol type="1">
<li><strong>Mark G. Sobell — <em>A Practical Guide to Linux Commands, Editors, and Shell Programming</em></strong> (or <strong>Matthew — <em>Beginning Linux Programming</em>, Chapters 1–5</strong>)
<ul>
<li><strong>Scope to read:</strong> Shell navigation (<code>cd</code>, <code>ls -la</code>), process control (<code>ps</code>, <code>bg</code>, <code>fg</code>, <code>kill</code>, <code>&amp;</code>), stream redirection (<code>&gt;</code>, <code>&gt;&gt;</code>, <code>|</code>), and text editors (<code>vi</code>/<code>vim</code>, <code>nano</code>, <code>micro</code>).</li>
<li><strong>Shell differences:</strong> Study the syntax variations between <code>bash</code> (environment variables via <code>export VAR=value</code>, aliases via <code>alias name='command'</code>) and <code>tcsh</code> (variables via <code>setenv VAR value</code>, aliases via <code>alias name 'command'</code>).</li>
<li><strong>Explicit exclusions:</strong> Skip sections covering <code>sed</code>, <code>awk</code>, <code>perl</code>, <code>emacs</code>, SQL databases, semaphores, pipes/sockets, and low-level POSIX calls.</li>
<li><strong>Networking &amp; security:</strong> Review remote connectivity commands (<code>ssh</code>, <code>sftp</code>, <code>traceroute</code>, <code>ping</code>) and securing server access via <code>/etc/hosts.deny</code>.</li>
</ul></li>
<li><strong>Norbert Schörghofer — <em>Lessons in Scientific Computing</em></strong>
<ul>
<li><strong>Chapter 1 (pp.&nbsp;25–35):</strong> Read the performance comparisons between compiled languages (C, Fortran 95) and interpreted environments (Python, NumPy, MATLAB, IDL), focusing on why inner loops require compiled binaries.</li>
</ul></li>
<li><strong>Language Foundations (Select Your Primary Language: C or Modern Fortran)</strong>
<ul>
<li><strong>If choosing C:</strong>
<ul>
<li><strong>Stephen G. Kochan — <em>Programming in C</em> (Chapters 7–11)</strong> or <strong>Kernighan &amp; Ritchie (K&amp;R) — <em>The C Programming Language</em> (Chapters 1–5):</strong> Focus on arrays, pointer arithmetic, memory addresses, and dynamic allocation via <code>malloc</code> and <code>free</code>.</li>
<li><strong>K. N. King — <em>C Programming: A Modern Approach</em> (Chapters 11, 12, &amp; 17):</strong> Study flattened 1D array indexing (<code>grid[i * N + j]</code>) versus jagged pointer arrays (<code>grid[i][j]</code>) to understand spatial cache locality.</li>
</ul></li>
<li><strong>If choosing Fortran:</strong>
<ul>
<li><strong>Stephen J. Chapman — <em>Fortran for Scientists and Engineers</em> (Chapters 1–8)</strong> (or <strong>Brainerd / Chivers</strong>): Study free-form source formatting, <code>implicit none</code>, array operations, modules, and case-insensitivity rules.</li>
<li><strong>Milan Curcic — <em>Modern Fortran: Building Efficient Parallel Applications</em> (Chapters 2–5):</strong> Focus on whole-array arithmetic, multidimensional array slices (<code>A(1:N:2)</code>), and intrinsic array functions.</li>
</ul></li>
<li><strong>For Python Interoperability:</strong>
<ul>
<li><strong>J. Izaac &amp; J. B. Wang — <em>Computational Quantum Mechanics</em> (Chapters 2 &amp; 3):</strong> Read Chapter 2 for Modern Fortran array foundations and Chapter 3 for scientific Python and wrapping compiled C/Fortran routines.</li>
</ul></li>
</ul></li>
</ol>
<hr>
</section>
<section id="phase-2-material-for-assignment-1-due-lecture-4" class="level3">
<h3 class="anchored" data-anchor-id="phase-2-material-for-assignment-1-due-lecture-4">Phase 2: Material for Assignment 1 (Due Lecture 4)</h3>
<p>Work through these readings to build the analytical physics formulations, asymptotic algorithmic proofs, and finite-difference stencils required for the four assignment problems:</p>
<section id="step-2a-flight-dynamics-and-aerobatic-loop-analysis-problem-1.1" class="level4">
<h4 class="anchored" data-anchor-id="step-2a-flight-dynamics-and-aerobatic-loop-analysis-problem-1.1">Step 2A: Flight Dynamics and Aerobatic Loop Analysis (Problem 1.1)</h4>
<ul>
<li><strong>Robert Resnick, David Halliday, &amp; Kenneth S. Krane (RHK) — <em>Physics, Vol. 1</em> (5th Ed.)</strong>
<ul>
<li><strong>Chapter 4 (§4.5):</strong> Kinematics of relative velocity and constructing airspeed-wind drift vector triangles: <span class="math inline">\(\mathbf{v}_{\text{ground}} = \mathbf{v}_{\text{plane}} + \mathbf{v}_{\text{wind}}\)</span>.</li>
<li><strong>Chapters 7 &amp; 8:</strong> Work, kinetic energy, and mechanical energy conservation along vertical arcs: <span class="math inline">\(v(y) = \sqrt{v_0^2 - 2gy}\)</span>.</li>
</ul></li>
<li><strong>John D. Anderson — <em>Introduction to Flight</em> (8th/9th Ed.)</strong>
<ul>
<li><strong>Chapter 5 (§5.13–§5.15):</strong> Normal load factor <span class="math inline">\(n = 1 + v^2/(gR)\)</span>, centripetal pull-up force balance, and apex weightlessness determining the circular radius <span class="math inline">\(R = v_0^2/(5g)\)</span>.</li>
<li><strong>Chapter 5 (§5.16):</strong> The <span class="math inline">\(V\text{–}n\)</span> flight envelope and dynamic stall speed scaling <span class="math inline">\(v_S(n) = v_{S,0}\sqrt{n}\)</span>.</li>
</ul></li>
<li><strong>John R. Taylor — <em>Classical Mechanics</em></strong>
<ul>
<li><strong>Chapters 1 &amp; 2 (§2.1–§2.4):</strong> Quadratic aerodynamic drag vectors <span class="math inline">\(\mathbf{F}_D = -\frac{1}{2}\rho C_D A v \mathbf{v}\)</span>.</li>
<li><strong>Chapter 3 (§3.1–§3.3):</strong> Momentum conservation and center-of-mass decoupling.</li>
</ul></li>
<li><strong>Bernard Etkin &amp; Lloyd Duff Reid — <em>Dynamics of Flight: Stability and Control</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 5 (§5.1–§5.6):</strong> Coupled longitudinal equations of motion in speed <span class="math inline">\(v(t)\)</span> and flight-path angle <span class="math inline">\(\theta(t)\)</span>, and load-dependent induced drag polar modeling: <span class="math inline">\(C_D = C_{D0} + K C_L^2\)</span>.</li>
</ul></li>
<li><strong>William H. Press et al.&nbsp;— <em>Numerical Recipes</em> (3rd Ed.) / Mark Newman — <em>Computational Physics</em></strong>
<ul>
<li><strong>Press et al., Chapter 16 (§16.1–§16.3)</strong> or <strong>Newman, Chapter 8 (§8.1–§8.4):</strong> Explicit fourth-order Runge–Kutta (RK4) integration with adaptive step-size control and trajectory closure checks at <span class="math inline">\(\theta = 2\pi\)</span>.</li>
</ul></li>
<li><strong>Vladimir Arnold — <em>Mathematical Methods of Classical Mechanics</em> (2nd Ed.)</strong>
<ul>
<li><strong>Chapter 3 (§12, §16):</strong> Clothoid (Euler spiral) curvature parameterization <span class="math inline">\(\kappa(s) = s/A^2\)</span> to eliminate unbounded normal jerk (<span class="math inline">\(\dot{n} \to \infty\)</span>).</li>
</ul></li>
</ul>
</section>
<section id="step-2b-multiphase-air-water-ballistics-problem-1.2" class="level4">
<h4 class="anchored" data-anchor-id="step-2b-multiphase-air-water-ballistics-problem-1.2">Step 2B: Multiphase Air-Water Ballistics (Problem 1.2)</h4>
<ul>
<li><strong>RHK — <em>Physics, Vol. 1</em> (5th Ed.)</strong>
<ul>
<li><strong>Chapter 15 (§15.1–§15.4):</strong> Fluid statics, hydrostatic pressure variation, Archimedes’ buoyancy, and effective gravity in water: <span class="math inline">\(g_{\text{eff}} = g(1 - \rho_w/\rho_p)\)</span>.</li>
</ul></li>
<li><strong>John R. Taylor — <em>Classical Mechanics</em></strong>
<ul>
<li><strong>Chapter 2 (§2.1–§2.4):</strong> Motion in resisting media and closed-form vertical terminal velocity <span class="math inline">\(v_t = \sqrt{2m g_{\text{eff}} / (\rho C_D A)}\)</span>.</li>
</ul></li>
<li><strong>Randall J. LeVeque — <em>Finite Difference Methods for Ordinary and Partial Differential Equations</em></strong>
<ul>
<li><strong>Chapters 1–3:</strong> Initial value problems across discontinuous interfaces and managing severe deceleration spikes across the air-water density boundary.</li>
</ul></li>
<li><strong>Press et al.&nbsp;— <em>Numerical Recipes</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 9 &amp; Chapter 16 (§16.6):</strong> Brent’s root-finding method for detecting the interface impact zero-crossing <span class="math inline">\(y(t^*)=0\)</span> and managing stiff differential equations.</li>
</ul></li>
</ul>
</section>
<section id="step-2c-vector-monotonicity-and-memory-optimization-problem-1.3" class="level4">
<h4 class="anchored" data-anchor-id="step-2c-vector-monotonicity-and-memory-optimization-problem-1.3">Step 2C: Vector Monotonicity and Memory Optimization (Problem 1.3)</h4>
<ul>
<li><strong>Thomas H. Cormen et al.&nbsp;(CLRS) — <em>Introduction to Algorithms</em> (3rd/4th Ed.)</strong>
<ul>
<li><strong>Chapter 3 (§3.1–§3.2) &amp; Chapter 4 (§4.1):</strong> Asymptotic growth notations (<span class="math inline">\(\Theta, \mathcal{O}, \Omega\)</span>), algebraic proof that naive pairwise comparisons scale as <span class="math inline">\(\sum_{i=1}^{N-1}(N-i) \in \Theta(N^2)\)</span>, and prefix reduction to a linear <span class="math inline">\(\Theta(N)\)</span> scan.</li>
</ul></li>
<li><strong>Donald E. Knuth — <em>The Art of Computer Programming, Vol. 2: Seminumerical Algorithms</em></strong>
<ul>
<li><strong>Chapters 3 &amp; 4:</strong> Discrete sequence scanning, loop invariants, and proof of single-pass running minimum optimization requiring <span class="math inline">\(\mathcal{O}(1)\)</span> auxiliary storage.</li>
</ul></li>
<li><strong>Randal E. Bryant &amp; David R. O’Hallaron — <em>Computer Systems: A Programmer’s Perspective (CS:APP)</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 5 (§5.7–§5.12):</strong> Program optimization, instruction-level parallelism (ILP), and loop unrolling.</li>
<li><strong>Chapter 6 (§6.2–§6.6):</strong> The memory hierarchy, 64-byte L1/L2/L3 cache lines, spatial locality, and avoiding cache misses during <span class="math inline">\(N \sim 10^7\)</span> element traversals.</li>
</ul></li>
</ul>
</section>
<section id="step-2d-second-derivative-stencil-truncation-and-roundoff-limits-problem-1.4" class="level4">
<h4 class="anchored" data-anchor-id="step-2d-second-derivative-stencil-truncation-and-roundoff-limits-problem-1.4">Step 2D: Second-Derivative Stencil Truncation and Roundoff Limits (Problem 1.4)</h4>
<ul>
<li><strong>Randall J. LeVeque — <em>Finite Difference Methods</em></strong>
<ul>
<li><strong>Chapter 1 (§1.1–§1.3):</strong> Taylor series expansions and analytical derivation of the 3-point central difference truncation error bound: <span class="math inline">\(E_{\text{trunc}} = \frac{h^2}{12}|f^{(4)}(\xi)|\)</span>.</li>
</ul></li>
<li><strong>Mark Newman — <em>Computational Physics</em></strong>
<ul>
<li><strong>Chapter 5 (§5.10):</strong> Subtractive floating-point roundoff cancellation: <span class="math inline">\(E_{\text{round}} = \frac{4\epsilon_{\text{mach}}}{h^2}|f|\)</span>, derivation of optimal step size <span class="math inline">\(h_{\text{opt}} \sim \epsilon_{\text{mach}}^{1/4}\)</span>, and generating the log-log error V-curve.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="phase-3-material-for-assignment-2-due-lecture-6" class="level3">
<h3 class="anchored" data-anchor-id="phase-3-material-for-assignment-2-due-lecture-6">Phase 3: Material for Assignment 2 (Due Lecture 6)</h3>
<p>Read these sources to implement stochastic Monte Carlo simulations and shared-memory parallel programming:</p>
<section id="step-3a-monte-carlo-integration-and-error-scaling" class="level4">
<h4 class="anchored" data-anchor-id="step-3a-monte-carlo-integration-and-error-scaling">Step 3A: Monte Carlo Integration and Error Scaling</h4>
<ul>
<li><strong>Mark Newman — <em>Computational Physics</em></strong>
<ul>
<li><strong>Chapter 10 (§10.1):</strong> Pseudo-random number generators, linear congruential generators (LCGs), random seeds, and uniform sampling.</li>
<li><strong>Chapter 10 (§10.2):</strong> Monte Carlo integration methods, including hit-or-miss and mean-value estimation of <span class="math inline">\(\pi\)</span>.</li>
<li><strong>Chapter 10 (§10.3):</strong> Statistical errors, the Central Limit Theorem, and proof of the dimension-independent <span class="math inline">\(\sigma \propto \frac{1}{\sqrt{N}}\)</span> convergence rate.</li>
</ul></li>
<li><strong>Press et al.&nbsp;— <em>Numerical Recipes</em> (3rd Ed.)</strong>
<ul>
<li><strong>Chapter 7 (§7.1–§7.3):</strong> Random number generation, period lengths, and eliminating LCG hyper-plane correlations.</li>
<li><strong>Chapter 15 (§15.1):</strong> Statistical modeling, sample variance, and confidence intervals.</li>
</ul></li>
</ul>
</section>
<section id="step-3b-openmp-loop-parallelization-and-2d-diffusion" class="level4">
<h4 class="anchored" data-anchor-id="step-3b-openmp-loop-parallelization-and-2d-diffusion">Step 3B: OpenMP Loop Parallelization and 2D Diffusion</h4>
<ul>
<li><strong>Georg Hager &amp; Gerhard Wellein — <em>Introduction to High Performance Computing for Scientists and Engineers</em></strong>
<ul>
<li><strong>Chapter 6 (§6.1–§6.2):</strong> The fork-join thread execution model and work-sharing loop constructs (<code>#pragma omp parallel for</code> in C, <code>!$omp parallel do</code> in Fortran).</li>
<li><strong>Chapter 6 (§6.3):</strong> Data scoping rules, thread-safety, distinguishing <code>shared</code> arrays from loop-private variables (<code>private</code>, <code>firstprivate</code>), and preventing data races.</li>
<li><strong>Chapter 6 (§6.4):</strong> Reduction operations (<code>reduction(+:sum)</code>) for accumulating multi-threaded Monte Carlo sums across CPU cores.</li>
</ul></li>
<li><strong>Milan Curcic — <em>Modern Fortran: Building Efficient Parallel Applications</em></strong>
<ul>
<li><strong>Chapters 11 &amp; 12:</strong> Parallelizing loops with OpenMP directives, chunk scheduling (<code>schedule(static)</code> vs.&nbsp;<code>schedule(dynamic)</code>), and SIMD compiler auto-vectorization.</li>
</ul></li>
<li><strong>Randall J. LeVeque — <em>Finite Difference Methods</em></strong>
<ul>
<li><strong>Chapter 9:</strong> Parabolic PDEs and explicit 2D 5-point Laplace stencil updates for the diffusion equation: <span class="math display">\[u_{i,j}^{n+1} = u_{i,j}^n + \Delta t \left( \frac{u_{i+1,j}^n - 2u_{i,j}^n + u_{i-1,j}^n}{\Delta x^2} + \frac{u_{i,j+1}^n - 2u_{i,j}^n + u_{i,j-1}^n}{\Delta y^2} \right)\]</span> Managing grid boundary updates in parallel and verifying the numerical CFL stability limit: <span class="math inline">\(\Delta t \le \frac{\Delta x^2}{4D}\)</span>.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="phase-4-midterm-exam-preparation-lecture-7" class="level3">
<h3 class="anchored" data-anchor-id="phase-4-midterm-exam-preparation-lecture-7">Phase 4: Midterm Exam Preparation (Lecture 7)</h3>
<p>The midterm exam is split into an 8% theoretical quiz and an 8% written problem-solving section (allowing 8 handwritten note pages / 4 double-sided sheets and a calculator). Complete these readings and code inspections in order:</p>
<ol type="1">
<li><strong>Hardware Architecture, Microprocessors, and Physical Bottlenecks (Quiz Scope)</strong>
<ul>
<li><strong>Paul E. Ceruzzi — <em>A History of Modern Computing</em> (Chapters 5 &amp; 6):</strong> Microprocessor development, Intel x86 architecture, the origins of Unix and Linux, and the growth of the Internet.</li>
<li><strong>Georg Hager &amp; Gerhard Wellein — <em>Introduction to High Performance Computing</em>:</strong>
<ul>
<li><strong>Chapter 1:</strong> Superscalar pipelines, clock frequency ceilings, and SIMD instruction registers.</li>
<li><strong>Chapter 2 (§2.1–§2.3):</strong> Arithmetic intensity (FLOPs per byte of DRAM transfer), cache line latency, and the memory bandwidth wall.</li>
<li><strong>Chapter 3:</strong> The breakdown of Dennard scaling around 2004–2005 due to leakage currents, the processor power wall, the shift to multi-core architectures, and the sustainability of Moore’s Law.</li>
</ul></li>
</ul></li>
<li><strong>Memory Models and Language Standards (Quiz &amp; Problem Scope)</strong>
<ul>
<li><strong>K. N. King — <em>C Programming: A Modern Approach</em> (Chapters 11, 12, 17):</strong> Contrast C row-major (lexicographical) contiguous buffer storage with Fortran column-major storage, and analyze why non-contiguous memory layouts degrade hardware prefetching.</li>
<li><strong>Compiler Toolchains &amp; Flags:</strong> Review GCC (<code>gcc</code>, <code>gfortran</code>), Intel (<code>icc</code>, <code>ifort</code>, <code>ifx</code>), and NVIDIA (<code>nvcc</code>, <code>nvfortran</code>) compiler optimization flags (<code>-O2</code>, <code>-O3</code>, <code>-fopenmp</code>, <code>-march=native</code>).</li>
</ul></li>
<li><strong>Algorithmic Puzzles and Instructor Code Repository (<code>progD57</code>)</strong>
<ul>
<li><strong>The 711 Numerical Puzzle (Lecture 4):</strong> Review the prime factorization of <span class="math inline">\(711 \times 10^6 = 2^6 \cdot 3^2 \cdot 5^6 \cdot 79\)</span> and how constraint pruning (isolating multiples of 79 with ordered loops <span class="math inline">\(a \le b \le c \le d\)</span>) eliminates brute-force <span class="math inline">\(\mathcal{O}(N^4)\)</span> search costs.</li>
<li><strong>Kruskal Counts &amp; Linked Lists (Lecture 4):</strong> Trace how deterministic hopping over card sequences maps directly to linked-list node chains in C pointers and Fortran array indices.</li>
<li><strong>Live Code Inspection:</strong> Download, compile, and run the professor’s sample codes at <code>[http://planets.utsc.utoronto.ca/~pawel/progD57](http://planets.utsc.utoronto.ca/~pawel/progD57)</code> for the 711 puzzle, Kruskal counts, OpenMP Monte Carlo <span class="math inline">\(\pi\)</span> calculations, and the parallel 2D diffusion stencil.</li>
<li><strong>Exam Archives:</strong> Review <code>mid-prep-2026.html</code> and the 2025 Midterm Exam solutions, paying close attention to quiz traps where incorrect technical terms are enclosed in quadruple asterisks (<code>****word****</code>).</li>
</ul></li>
</ol>



<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/igor-kan\.github\.io\/phyd57h3");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; From: https://gemini.google.com/app/d5fdbfc39d798c48</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu"># you asked</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>message time: 2026-10-03 14<span class="sc">:54:</span>40</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>https://planets.utsc.utoronto.ca/~pawel/PHYD57/ </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>1   Structure and scope of the course</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    Syllabus of PHYD57</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    Numerical Comp. in Physical Sciences: History and Contemporary efforts</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>2   HPC: need for speed, why and how</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    History and modernity: microprocessors, Unix, Linux, and Internet</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    Intro to Linux (CentOS)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    Command line interface and shells (bash and tcsh)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    Text editors: vi, nano, gedit, micro</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>3   Connectivity (ssh &amp; sftp, traceroute &amp; ping)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    Securing the linux system against break-ins via /etc/hosts.deny</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    Basic Linux shells and commands (bash, tcsh, cd, ls, ps, cd, &amp;, bg, fg, </span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>       alias, export/setenv, rm, output redirection to file via &gt;)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    Getting more info: manual pages (man), -h, --help, or -help modifiers</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    Recommended compilers:  GNU: gcc, gfortran; Intel: icc, ifort or ifx; </span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>            Nvidia: nvcc/nvc++, nvfortran (formerly pgf95) </span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    Simple program in C, Fortran95, Python, Matlab, IDL (Schoerghofer,p.30)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    More complex program, example of HPC:</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        2nd order Laplace operator stencil for the diffusion equation</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    Speed comparison of C/F95 with Python &amp; Numpy: why we learn HPC</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>4   C and Fortran 95 - compilers, basic usage  </span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    Numerical puzzle of 711 - learning C and Fortran</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    Kruskal counts and their connection to linked lists</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    Coding Kruskal counts trick in Python and Fortran </span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    C: Language overview, compilers</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    Integration with Python: calling C from Python</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    Examples of programs</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>5   Dicussion of the solutions of A2 assignment set </span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    More Fortran. Monte Carlo method (MtC)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    Examples of programs: Random numbers and MtC (finding π)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    Slow convergence: const./sqrt(N) scaling of error in MtC</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    Parallel execution on CPU using OpenMP fork-join method in loops</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    Parallel implementations: in-depth diffusion equation </span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>6   Modern computing in the era of Integrated Circuits</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    2000s: Appearence of barriers to single-thread computing</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>    The only solution: parallelism </span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    Moore's law: sustainable or not? also look at the website in details, its subpages etc.</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="fu"># gemini response</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>The course portal for **PHYD57 (Advanced Computational Methods in Physics)** hosted at <span class="in">`planets.utsc.utoronto.ca/~pawel/PHYD57/`</span> serves as the primary centralized hub for lecture syllabi, computing cluster access rules, reading references, and project descriptions curated by Prof. Pawel Artymowicz.</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1. Website Architecture and Subpage Resources</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>The course site operates as an unstyled, direct academic directory containing links to syllabi, project documentation, external texts, and hidden resource pages:</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Central Course Hub (`/PHYD57/`):** Contains the official syllabus text file, lecture schedule, language policies, assignment submission criteria, and midterm/final examination rules.</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**PHYD57 References Page (`References` subpage):** Hosts recommended readings and technical PDFs covering core languages and computing history:</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Lessons in Scientific Computing* by Norbert Schörghofer (specifically pages 25–35 detailing runtime benchmarks between C, Modern Fortran, and Python).</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Computational Quantum Mechanics* by J. Izaac and J. B. Wang (Chapter 2 for Modern Fortran syntax and Chapter 3 for scientific Python).</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*The Definitive Guide to CentOS* by Membrey (Chapter 3, covering headless server setups and remote access).</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*A History of Modern Computing* by Paul E. Ceruzzi.</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Programming for Computations – Python* by Svein Linge and Aslak Tveito.</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Project Dossiers and Hidden Subdirectories:**</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Aerodynamics &amp; Flight Dynamics (`/~pawel/s/`):** A hidden directory (accessed by replacing <span class="in">`PHYD57`</span> with <span class="in">`s`</span> in the URL) dedicated to the Smolensk Tu-154 crash aerodynamic reconstruction, Prandtl lifting-line theory, and 3D vortex panel methods.</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Smoothed Particle Hydrodynamics (SPH):** Papers by J. J. Monaghan (1997, 2005) and Stephan Rosswog (*Astrophysical SPH*) covering Lagrangian fluid modeling.</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**N-Body and Galactic Dynamics:** Dynamics references based on Binney &amp; Tremaine’s *Galactic Dynamics*, alongside CUDA N-body integration engines.</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Fast Fourier Transforms (FFT):** Reference texts by E. Oran Brigham and NVIDIA’s <span class="in">`CUFFT_Library.pdf`</span> documentation for solving Poisson and gravitational potential convolutions in $\mathcal{O}(N \ln N)$ time.</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Structural Mechanics (Golden Gate Project):** Suspension bridge modeling based on Gimsing (*Cable Supported Bridges*) and Gazzola (*Mathematical Models for Suspension Bridges*).</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2. Full 12-Week Course Curriculum</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>The lecture and tutorial track advances from POSIX command-line mechanics to multi-core threading and massively parallel GPU acceleration:</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Week <span class="pp">|</span> Lecture Topics <span class="pp">|</span> Practical &amp; Computational Focus <span class="pp">|</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="pp">| :---</span> <span class="pp">| :---</span> <span class="pp">| :---</span> <span class="pp">|</span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **1** <span class="pp">|</span> Course Scope &amp; History of Numerical Computing <span class="pp">|</span> Overview of physical simulation paradigms and course logistics. <span class="pp">|</span></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **2** <span class="pp">|</span> Microprocessor Evolution &amp; Unix/Linux Essentials <span class="pp">|</span> CentOS environment, bash/tcsh shells, and terminal text editors (<span class="in">`vi`</span>, <span class="in">`nano`</span>, <span class="in">`gedit`</span>, <span class="in">`micro`</span>). <span class="pp">|</span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **3** <span class="pp">|</span> Networking &amp; Low-Level Language Benchmarking <span class="pp">|</span> SSH/SFTP, <span class="in">`/etc/hosts.deny`</span> security, GNU/Intel/NVIDIA compiler toolchains, 2nd-order Laplace diffusion stencils, and C/Fortran vs. Python/NumPy execution speed comparisons. <span class="pp">|</span></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **4** <span class="pp">|</span> C &amp; Modern Fortran 95 Implementations <span class="pp">|</span> Compiler optimization flags, the Numerical Puzzle of 711, Kruskal counts, linked list mechanics, and calling C routines from Python. <span class="pp">|</span></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **5** <span class="pp">|</span> Monte Carlo Integration &amp; Early OpenMP <span class="pp">|</span> Pseudo-random number generators, calculating $\pi$, $\mathcal{O}(N^{-1/2})$ statistical error convergence, OpenMP fork-join loops, and parallelizing the 2D heat diffusion equation. <span class="pp">|</span></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **6** <span class="pp">|</span> Integrated Circuit Scaling &amp; Hardware Limits <span class="pp">|</span> Dennard scaling breakdown, single-thread performance walls, multi-core chip architectures, and the sustainability of Moore's Law. <span class="pp">|</span></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **7** <span class="pp">|</span> Many-Core Architectures &amp; Memory Models <span class="pp">|</span> Introduction to group project (A4) options, Intel Many Integrated Core (MIC / Xeon Phi), supercomputing clusters, and row-major (C) vs. column-major (Fortran) array ordering. <span class="pp">|</span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **8** <span class="pp">|</span> Advanced OpenMP &amp; Single-Node Bottlenecks <span class="pp">|</span> Stack overflow segmentation faults, CPU compute vs. RAM bandwidth constraints, DISLIN graphics library, wave equations, linked-list neighbor searches, and SPH implementations. <span class="pp">|</span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **9** <span class="pp">|</span> Vectorization, MIC &amp; Introduction to CUDA <span class="pp">|</span> Compiler auto-vectorization reports, optically thick disk radiation (IRI), N-body gravitational integration, and simple neural net stabilization (inverted pendulum problem). <span class="pp">|</span></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **10** <span class="pp">|</span> Astrophysical Disks, Hydrodynamics &amp; FFT <span class="pp">|</span> Protoplanetary disk simulations, Eulerian vs. Lagrangian fluids (<span class="in">`fluidsGL`</span>), gravitational potentials via FFT convolutions, zero-padding/aliasing, and CUDA Fortran kernels. <span class="pp">|</span></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **11** <span class="pp">|</span> Massively Parallel CUDA &amp; Machine Learning <span class="pp">|</span> CUDA C/C++ thread hierarchies, tetrahedrons puzzle, intro to MPI, neural network dimensionality, overfitting, and the Nelder–Mead Simplex optimization algorithm. <span class="pp">|</span></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **12** <span class="pp">|</span> Research Project Capstone <span class="pp">|</span> In-class presentations and evaluations of student A4 group research projects. <span class="pp">|</span></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3. Computing Architecture and Toolchains</span></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>The course centers on direct access to departmental research clusters housed in the Science Wing and BV Building at UTSC:</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Cluster Environments:**</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span><span class="in">`art-1`</span> and <span class="in">`art-2`</span>: Multi-core servers running CentOS 6 with <span class="in">`tcsh`</span> as the default shell. Users authenticate over legacy SSH ciphers (<span class="in">`-o HostKeyAlgorithms=+ssh-dss`</span>).</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span><span class="in">`art-16`</span>: Modern GPU accelerator nodes running Rocky Linux 9 with modern <span class="in">`bash`</span>.</span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span><span class="in">`phi`</span>: Multi-core compute nodes equipped with Intel Xeon Phi (Many Integrated Core / MIC) co-processors.</span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Compiler Suites:**</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**GNU Compiler Collection (GCC):** <span class="in">`gcc`</span>, <span class="in">`g++`</span>, and <span class="in">`gfortran`</span>.</span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**NVIDIA HPC SDK:** <span class="in">`nvcc`</span>, <span class="in">`nvc`</span>, <span class="in">`nvc++`</span>, and <span class="in">`nvfortran`</span> (modern replacement for PGI <span class="in">`pgf90`</span>/<span class="in">`pgf95`</span>).</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Intel oneAPI:** <span class="in">`icx`</span>, <span class="in">`icpx`</span>, and <span class="in">`ifx`</span> (modern replacement for legacy <span class="in">`icc`</span> and <span class="in">`ifort`</span>).</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Language Policy:**</span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Passive Requirement:* Mandatory ability to read, trace, and debug both C and Modern Fortran (90/95/2003/2008) in lecture codes and exams.</span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Active Requirement:* Students select either C/C++ or Modern Fortran as their primary language for homework and exams.</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Python:* Restricted to an auxiliary role (prototyping, driver scripts, plotting data with Matplotlib, and testing numerical accuracy) rather than writing inner simulation kernels.</span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4. Course Deliverables and Grading Scheme</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a>Term evaluations balance numerical physics problem sets, multi-threaded coding assignments, and in-person exams:</span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Deliverable <span class="pp">|</span> Weight <span class="pp">|</span> Key Deadlines &amp; Structural Parameters <span class="pp">|</span></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="pp">| :---</span> <span class="pp">| :---</span> <span class="pp">| :---</span> <span class="pp">|</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Assignment 1 (A1)** | **7%** <span class="pp">|</span> Due at 11:00 AM on Lecture 4. Covers flight mechanics, air-water ballistics, $\mathcal{O}(N)$ optimization, and 2nd-derivative stencil truncation error. <span class="pp">|</span></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Assignment 2 (A2)** | **7%** <span class="pp">|</span> Due at 11:00 AM on Lecture 6. Centers on Monte Carlo simulations, convergence rates, and initial OpenMP loop parallelization. <span class="pp">|</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Midterm Exam** | **16%** <span class="pp">|</span> Held in-class during Lecture 7 (11:10–12:10 AM). Split evenly: 8% written problem solving and 8% theoretical quiz. <span class="pp">|</span></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Assignment 3 (A3)** | **7%** <span class="pp">|</span> Due at 11:00 AM on Lecture 10. Focuses on advanced OpenMP, FFT convolutions, and initial CUDA GPU kernel development. <span class="pp">|</span></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Group Project (A4)** | **23%** <span class="pp">|</span> Groups finalized by Lecture 6; project presentations during Lecture 12. Involves developing an end-to-end HPC simulation (SPH fluids, N-body dynamics, aerodynamics, or bridge oscillations). <span class="pp">|</span></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Final Exam** | **40%** <span class="pp">|</span> In-person 3-hour examination split into two sections: ~1.5 hours closed-book written theory and quiz, followed by ~1.5 hours of live coding on a personal laptop or via remote SSH to the <span class="in">`art`</span> cluster. Students may bring up to 8 handwritten note pages (4 double-sided sheets). <span class="pp">|</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a>*Submission Policy:* Work submitted more than 3 hours past the 11:00 AM deadline receives an automatic 50% deduction, with no extensions granted due to in-class solution discussions during tutorials. Academic illness accommodations require an official Verification of Illness (VOI) form or ACORN self-declaration.</span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a><span class="fu"># you asked</span></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a>message time: 2026-10-03 14<span class="sc">:56:</span>57</span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a>what chapters/sectiosn i need to read from suggested or other soruces textbooks or onlie to prepare for midterm, and cover material needed to get a1, a2 assignmetns done</span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a><span class="fu"># gemini response</span></span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a>To successfully complete **Assignment 1 (A1)**, **Assignment 2 (A2)**, and pass both the written problem-solving and theoretical quiz portions of the **Midterm Exam** (Lectures 1–6), your reading must cover three integrated areas: **analytical and numerical physics modeling**, **low-level systems and memory architectures (C &amp; Modern Fortran)**, and **parallel execution (OpenMP)**.</span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part 1: Readings for Assignment 1 (A1)</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a>*Due Lecture 4; covers flight dynamics, multiphase ballistics, algorithmic complexity, and finite-difference error scaling.*</span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Problem 1.1: F-16 Aerobatic Loop Analysis</span></span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**John D. Anderson — *Introduction to Flight* (8th/9th Ed.)**</span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 5 (§5.13–§5.15): Accelerated Flight &amp; Pull-up Maneuvers:** Derives normal load factor $n = 1 + v^2/(gR)$, centripetal pull-up force balance, and apex weightlessness yielding the circular radius relation $R = v_0^2/(5g)$.</span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 5 (§5.16): The $V\text{–}n$ Flight Envelope:** Explains structural load limits and dynamic stall speed scaling $v_S(n) = v_{S,0}\sqrt{n}$.</span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Bernard Etkin &amp; Lloyd Duff Reid — *Dynamics of Flight: Stability and Control* (3rd Ed.)**</span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 5 (§5.1–§5.6): Vertical-Plane Trajectory Dynamics:** Formulates the coupled longitudinal equations of motion in speed $v(t)$ and flight-path angle $\theta(t)$ under quadratic drag and load-dependent induced drag ($C_D = C_{D0} + K C_L^2$).</span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**William H. Press et al. — *Numerical Recipes: The Art of Scientific Computing* (3rd Ed.)**</span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 16 (§16.1–§16.3): Runge–Kutta &amp; Adaptive Step-Size Control:** Explains how to integrate non-linear coupled ODEs with explicit loop closure checks at $\theta = 2\pi$.</span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Robert Resnick, David Halliday, &amp; Kenneth S. Krane — *Physics, Vol. 1* (5th Ed.)**</span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 4 (§4.5) &amp; Chapters 7–8:** Airspeed vector triangles under wind shear and mechanical work-energy conservation ($v(y) = \sqrt{v_0^2 - 2gy}$).</span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Vladimir Arnold — *Mathematical Methods of Classical Mechanics* (2nd Ed.)** *(Advanced/Trans-Syllabus)*</span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 3 (§12, §16):** Clothoid (Euler spiral) curvature parameterization ($\kappa(s) = s/A^2$) to eliminate unbounded normal jerk ($\dot{n} \to \infty$).</span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Problem 1.2: Multiphase Air-Water Ballistics</span></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**John R. Taylor — *Classical Mechanics***</span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 2 (§2.1–§2.4): Motion in Resisting Media:** Formulates 1D/2D quadratic aerodynamic drag ($\mathbf{F}_D = -\frac{1}{2}\rho C_D A v \mathbf{v}$) and closed-form vertical terminal velocity $v_t = \sqrt{2m g_{\text{eff}} / (\rho C_D A)}$.</span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Resnick, Halliday, &amp; Krane — *Physics, Vol. 1* (5th Ed.)**</span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 15 (§15.1–§15.4): Fluid Statics &amp; Buoyancy:** Derives Archimedes’ principle and effective gravitational acceleration in water: $g_{\text{eff}} = g(1 - \rho_w/\rho_p)$.</span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Randall J. LeVeque — *Finite Difference Methods for Ordinary and Partial Differential Equations***</span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapters 1–3: Initial Value Problems &amp; Discontinuous Interfaces:** Staggered time-stepping across discontinuous media boundaries (the $\sim 800\times$ density jump at $y=0$).</span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Press et al. — *Numerical Recipes* (3rd Ed.)**</span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 9 &amp; Chapter 16 (§16.6): Root Finding &amp; Stiff Systems:** Brent’s method for zero-crossing detection to pinpoint the air-water impact time $t^*$ without step-overs, along with handling stiff deceleration spikes.</span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Problem 1.3: Vector Monotonicity &amp; Subsegment Growth</span></span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Thomas H. Cormen et al. (CLRS) — *Introduction to Algorithms* (3rd/4th Ed.)**</span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 3 (§3.1–§3.2) &amp; Chapter 4 (§4.1): Asymptotic Growth &amp; Maximum Subarray:** Formal algebraic proofs comparing naive pairwise $\sum_{i=1}^{N-1}(N-i) = \frac{N(N-1)}{2} \in \Theta(N^2)$ against single-pass $\Theta(N)$ running-minimum scans with $\mathcal{O}(1)$ storage.</span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Randal E. Bryant &amp; David R. O'Hallaron — *Computer Systems: A Programmer's Perspective (CS:APP)* (3rd Ed.)**</span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 5: Optimizing Program Performance:** Instruction-level parallelism (ILP), unrolling loops, branch predictability, and eliminating memory stalls.</span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 6: The Memory Hierarchy:** 64-byte L1/L2/L3 cache lines, spatial/temporal locality, and avoiding strided cache thrashing during multi-million-element traversals.</span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Problem 1.4: Second-Derivative Stencil Limits</span></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Randall J. LeVeque — *Finite Difference Methods for Ordinary and Partial Differential Equations***</span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 1 (§1.1–§1.3): Truncation Error &amp; Taylor Series:** Deriving the second-order truncation error bound ($E_{\text{trunc}} = \frac{h^2}{12}|f^{(4)}(\xi)|$) for the 3-point central difference stencil.</span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Mark Newman — *Computational Physics***</span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 5 (§5.10): Numerical Derivatives &amp; Roundoff Error:** Analytical derivation of catastrophic subtractive cancellation ($E_{\text{round}} = 4\epsilon_{\text{mach}}|f| / h^2$), proving the optimal step size minimizes at $h_{\text{opt}} \sim \epsilon_{\text{mach}}^{1/4}$, and plotting the log-log error V-curve.</span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Schörghofer — *Lessons in Scientific Computing* (CRC 2019)**</span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 1 (pp. 25–35):** Benchmarking compiled C/Fortran stencils against Python/NumPy.</span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part 2: Readings for Assignment 2 (A2)</span></span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a>*Due Lecture 6; covers Monte Carlo methods, PRNGs, $1/\sqrt{N}$ error convergence, and OpenMP multi-threading.*</span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Monte Carlo Integration &amp; Random Number Generation</span></span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Mark Newman — *Computational Physics***</span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 10 (§10.1–§10.3): Random Numbers &amp; Monte Carlo Integration:**</span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§10.1:* Linear congruential generators (LCGs), pseudo-random sequences, seeds, and uniform distribution sampling.</span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§10.2:* Monte Carlo evaluation of definite integrals (e.g., finding $\pi$ via circle-in-a-square hit-or-miss and mean-value integration).</span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§10.3:* Statistical errors and the Central Limit Theorem: rigorous proof of the slow $\sigma \propto \frac{1}{\sqrt{N}}$ error scaling law independent of spatial dimensionality.</span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Press et al. — *Numerical Recipes* (3rd Ed.)**</span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 7 (§7.1–§7.3): Random Numbers:** Uniform random deviates, period lengths, avoiding defective LCG artifacts (Marsaglia planes).</span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 15 (§15.1): Modeling of Data:** Statistical variance, sample standard deviations, and confidence intervals for stochastic physical simulations.</span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a><span class="fu">#### OpenMP Loop Parallelization &amp; 2D Diffusion</span></span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Georg Hager &amp; Gerhard Wellein — *Introduction to High Performance Computing for Scientists and Engineers***</span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 6: Shared-Memory Parallel Programming with OpenMP:**</span>
<span id="cb2-210"><a href="#cb2-210" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§6.1–§6.2:* The fork-join thread execution model, parallel regions, and work-sharing loops (<span class="in">`#pragma omp parallel for`</span> in C, <span class="in">`!$omp parallel do`</span> in Fortran).</span>
<span id="cb2-211"><a href="#cb2-211" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§6.3:* Data scoping rules: distinguishing <span class="in">`shared`</span> memory arrays from loop-private variables (<span class="in">`private`</span>, <span class="in">`firstprivate`</span>), thread safety, and preventing data races.</span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>*§6.4:* Reduction clauses (<span class="in">`reduction(+:sum)`</span>): how multi-threaded Monte Carlo loops accumulate partial sums across cores without mutex lock contention.</span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Milan Curcic — *Modern Fortran: Building Efficient Parallel Applications***</span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 11 &amp; 12: Parallelism with OpenMP &amp; Hardware Vectors:** Implementing OpenMP directives over multidimensional Fortran arrays and understanding loop chunk scheduling (<span class="in">`schedule(static)`</span> vs <span class="in">`schedule(dynamic)`</span>).</span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**LeVeque — *Finite Difference Methods***</span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 9: Diffusion Equations &amp; Parabolic PDEs:** Setting up the explicit 2D 5-point Laplace stencil:</span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a>        $$u_{i,j}^{n+1} = u_{i,j}^n + \Delta t \left( \frac{u_{i+1,j}^n - 2u_{i,j}^n + u_{i-1,j}^n}{\Delta x^2} + \frac{u_{i,j+1}^n - 2u_{i,j}^n + u_{i,j-1}^n}{\Delta y^2} \right)$$</span>
<span id="cb2-218"><a href="#cb2-218" aria-hidden="true" tabindex="-1"></a>        Parallelizing grid update loops with OpenMP, managing inner vs. boundary points, and verifying the CFL stability criterion ($\Delta t \le \frac{\Delta x^2}{4D}$).</span>
<span id="cb2-219"><a href="#cb2-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-220"><a href="#cb2-220" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-221"><a href="#cb2-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-222"><a href="#cb2-222" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part 3: Readings for the Midterm Exam</span></span>
<span id="cb2-223"><a href="#cb2-223" aria-hidden="true" tabindex="-1"></a>*Held in Lecture 7; 16% of total grade (8% written problem solving + 8% multiple-choice/fill-in-the-blank quiz). Allowed aid: 8 handwritten note pages (4 double-sided sheets) and a calculator.*</span>
<span id="cb2-224"><a href="#cb2-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-225"><a href="#cb2-225" aria-hidden="true" tabindex="-1"></a><span class="fu">#### A. Microprocessor History, Hardware Architecture &amp; Physical Limits (Quiz Scope)</span></span>
<span id="cb2-226"><a href="#cb2-226" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Paul E. Ceruzzi — *A History of Modern Computing* (2nd Ed.)**</span>
<span id="cb2-227"><a href="#cb2-227" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapters 5 &amp; 6:** Transition from mainframes to microprocessors, Intel x86 architecture evolution, Unix/Linux origins, and the rise of the Internet.</span>
<span id="cb2-228"><a href="#cb2-228" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Hager &amp; Wellein — *Introduction to High Performance Computing***</span>
<span id="cb2-229"><a href="#cb2-229" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 1: Modern Processors:** Pipelining, superscalar execution, clock frequency limits, and SIMD registers.</span>
<span id="cb2-230"><a href="#cb2-230" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 2 (§2.1–§2.3): Memory Hierarchies &amp; Bottlenecks:** Memory wall, arithmetic intensity (FLOPs per byte of DRAM transfer), and L1/L2/L3 cache latency vs. main memory bandwidth.</span>
<span id="cb2-231"><a href="#cb2-231" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 3: Parallel Computers:** Dennard scaling breakdown (leakage currents and the thermal "power wall" around 2004–2005), multi-core CPUs as the only path forward, and the operational meaning of Moore's Law (transistor count scaling vs. single-thread frequency stagnation).</span>
<span id="cb2-232"><a href="#cb2-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-233"><a href="#cb2-233" aria-hidden="true" tabindex="-1"></a><span class="fu">#### B. Linux CLI, Networking &amp; System Security (Quiz Scope)</span></span>
<span id="cb2-234"><a href="#cb2-234" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Scott Membrey — *The Definitive Guide to CentOS***</span>
<span id="cb2-235"><a href="#cb2-235" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 3: Working with the Shell &amp; Remote Systems:**</span>
<span id="cb2-236"><a href="#cb2-236" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>Bash vs. tcsh shell environments, environment variables (<span class="in">`export`</span> vs. <span class="in">`setenv`</span>), aliases, process management (<span class="in">`ps`</span>, <span class="in">`&amp;`</span>, <span class="in">`bg`</span>, <span class="in">`fg`</span>, <span class="in">`kill`</span>), and stream redirection (<span class="in">`&gt;`</span>, <span class="in">`&gt;&gt;`</span>, <span class="in">`|`</span>).</span>
<span id="cb2-237"><a href="#cb2-237" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>Remote connectivity tools: <span class="in">`ssh`</span> and <span class="in">`sftp`</span> port mechanics, <span class="in">`ping`</span>, <span class="in">`traceroute`</span>, and MTU limits.</span>
<span id="cb2-238"><a href="#cb2-238" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>Security mechanisms: Securing access through <span class="in">`/etc/hosts.deny`</span> and <span class="in">`/etc/hosts.allow`</span> TCP wrappers.</span>
<span id="cb2-239"><a href="#cb2-239" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>Text editor fluency: Command modes in <span class="in">`vi`</span>, basic usage of <span class="in">`nano`</span> and <span class="in">`micro`</span>.</span>
<span id="cb2-240"><a href="#cb2-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-241"><a href="#cb2-241" aria-hidden="true" tabindex="-1"></a><span class="fu">#### C. Language Mechanics, Memory Models &amp; Compiler Suites (Quiz &amp; Written Scope)</span></span>
<span id="cb2-242"><a href="#cb2-242" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Norbert Schörghofer — *Lessons in Scientific Computing***</span>
<span id="cb2-243"><a href="#cb2-243" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 1 (§1.1–§1.4, pp. 1–35): Languages &amp; Computational Trade-offs:** Language performance taxonomy (C, Fortran 95, Python, NumPy, MATLAB, IDL); how interpreted dynamic typing incurs massive loop interpretation penalties compared to compiled binaries.</span>
<span id="cb2-244"><a href="#cb2-244" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**J. Izaac &amp; J. B. Wang — *Computational Quantum Mechanics***</span>
<span id="cb2-245"><a href="#cb2-245" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 2 (pp. 35–75): Modern Fortran Foundations:** Module design, strict typing (<span class="in">`implicit none`</span>), array slices (<span class="in">`A(1:N:2)`</span>), dynamic allocation (<span class="in">`allocate`</span>/<span class="in">`deallocate`</span>), and intrinsic math functions.</span>
<span id="cb2-246"><a href="#cb2-246" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapter 3 (pp. 77–110): Scientific Python:** NumPy vectorized arrays, SciPy libraries, and calling compiled C/Fortran libraries via Python wrappers (<span class="in">`ctypes`</span>, <span class="in">`f2py`</span>).</span>
<span id="cb2-247"><a href="#cb2-247" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**K. N. King — *C Programming: A Modern Approach* (2nd Ed.)**</span>
<span id="cb2-248"><a href="#cb2-248" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**Chapters 11, 12, &amp; 17: Pointers, Arrays, and Dynamic Memory:**</span>
<span id="cb2-249"><a href="#cb2-249" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>Pointer arithmetic and array memory layout: C row-major (lexicographical) order versus Fortran column-major order.</span>
<span id="cb2-250"><a href="#cb2-250" aria-hidden="true" tabindex="-1"></a><span class="ss">        *   </span>1D flattened contiguous buffers (<span class="in">`grid[i * N + j]`</span>) versus jagged pointer arrays (<span class="in">`grid[i][j]`</span>), and why jagged arrays destroy cache locality.</span>
<span id="cb2-251"><a href="#cb2-251" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Compiler Manuals &amp; Optimization Flags (GCC, Intel, NVIDIA SDK):**</span>
<span id="cb2-252"><a href="#cb2-252" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>GNU (<span class="in">`gcc`</span>, <span class="in">`gfortran`</span>), Intel (<span class="in">`icc`</span>, <span class="in">`ifort`</span>, <span class="in">`ifx`</span>), and NVIDIA (<span class="in">`nvcc`</span>, <span class="in">`nvfortran`</span> / formerly PGI <span class="in">`pgf95`</span>).</span>
<span id="cb2-253"><a href="#cb2-253" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>Optimization flags: <span class="in">`-O2`</span>, <span class="in">`-O3`</span>, <span class="in">`-march=native`</span>, loop unrolling, and <span class="in">`-fopenmp`</span> / <span class="in">`-qopenmp`</span>.</span>
<span id="cb2-254"><a href="#cb2-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-255"><a href="#cb2-255" aria-hidden="true" tabindex="-1"></a><span class="fu">#### D. Algorithmic Puzzles &amp; Problem-Solving (Written &amp; Quiz Scope)</span></span>
<span id="cb2-256"><a href="#cb2-256" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**The Numerical Puzzle of 711 (Lecture 4):**</span>
<span id="cb2-257"><a href="#cb2-257" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Concept:* Four items whose sum is $\$7.11$ and product is $\$7.11$ (in cents: $a+b+c+d=711$ and $a \cdot b \cdot c \cdot d = 711,000,000$).</span>
<span id="cb2-258"><a href="#cb2-258" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Focus:* Prime factorization of $711 \times 10^6 = 2^6 \cdot 3^2 \cdot 5^6 \cdot 79$. Understand analytical constraint pruning (isolating multiples of 79, ordering $a \le b \le c \le d$) to turn a brute-force $711^4 \approx 2.5 \times 10^{11}$ loop into an efficient multi-loop running in milliseconds in C/Fortran.</span>
<span id="cb2-259"><a href="#cb2-259" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Kruskal Counts &amp; Linked Lists (Lecture 4):**</span>
<span id="cb2-260"><a href="#cb2-260" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>*Concept:* Coupling card-counting permutations and word hops into linked-list node chains. Review pointer references in C and indexed target jumping in Fortran.</span>
<span id="cb2-261"><a href="#cb2-261" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>**Past Midterm Archive &amp; Course Codes:**</span>
<span id="cb2-262"><a href="#cb2-262" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**`mid-prep-2026.html` and 2025 Midterm Exam Solutions:** Carefully inspect past quiz traps (such as identifying incorrect technical terms inside quadruple asterisks `****word****`).</span>
<span id="cb2-263"><a href="#cb2-263" aria-hidden="true" tabindex="-1"></a><span class="ss">    *   </span>**`[http://planets.utsc.utoronto.ca/~pawel/progD57](http://planets.utsc.utoronto.ca/~pawel/progD57)`:** Run, inspect, and benchmark the professor’s codes for the 711 puzzle, Kruskal counts, 2D diffusion OpenMP stencils, and Monte Carlo $\pi$ estimation.</span>
<span id="cb2-264"><a href="#cb2-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-265"><a href="#cb2-265" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-266"><a href="#cb2-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-267"><a href="#cb2-267" aria-hidden="true" tabindex="-1"></a><span class="fu">### Master Reading Checklist Prior to Midterm</span></span>
<span id="cb2-268"><a href="#cb2-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-269"><a href="#cb2-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-270"><a href="#cb2-270" aria-hidden="true" tabindex="-1"></a><span class="in">Pre-Midterm Reading Schedule:</span></span>
<span id="cb2-271"><a href="#cb2-271" aria-hidden="true" tabindex="-1"></a><span class="in">├── Week 1–2 (Linux, Compilers &amp; Languages)</span></span>
<span id="cb2-272"><a href="#cb2-272" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Membrey: Ch 3 (CentOS, shells, ssh, /etc/hosts.deny)</span></span>
<span id="cb2-273"><a href="#cb2-273" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Schörghofer: Ch 1 (pp. 1–35, language comparison)</span></span>
<span id="cb2-274"><a href="#cb2-274" aria-hidden="true" tabindex="-1"></a><span class="in">│   └── Izaac &amp; Wang: Ch 2 &amp; 3 (Fortran 95 &amp; Python C-bindings)</span></span>
<span id="cb2-275"><a href="#cb2-275" aria-hidden="true" tabindex="-1"></a><span class="in">├── Week 3–4 (A1 Preparation: Dynamics, Stencils, Algorithms)</span></span>
<span id="cb2-276"><a href="#cb2-276" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Anderson: Ch 5 (§5.13–§5.16, loop dynamics &amp; stall)</span></span>
<span id="cb2-277"><a href="#cb2-277" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Taylor: Ch 2 (§2.1–§2.4, quadratic drag &amp; terminal velocity)</span></span>
<span id="cb2-278"><a href="#cb2-278" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── CLRS: Ch 3 &amp; 4 (asymptotic proofs for monotonicity scan)</span></span>
<span id="cb2-279"><a href="#cb2-279" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Bryant &amp; O'Hallaron: Ch 5 &amp; 6 (cache lines &amp; spatial locality)</span></span>
<span id="cb2-280"><a href="#cb2-280" aria-hidden="true" tabindex="-1"></a><span class="in">│   └── LeVeque: Ch 1 &amp; Newman: Ch 5 (stencil truncation &amp; roundoff envelope)</span></span>
<span id="cb2-281"><a href="#cb2-281" aria-hidden="true" tabindex="-1"></a><span class="in">├── Week 5–6 (A2 Preparation: Monte Carlo &amp; OpenMP)</span></span>
<span id="cb2-282"><a href="#cb2-282" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Newman: Ch 10 (random numbers, LCGs, 1/√N error scaling)</span></span>
<span id="cb2-283"><a href="#cb2-283" aria-hidden="true" tabindex="-1"></a><span class="in">│   ├── Hager &amp; Wellein: Ch 6 (OpenMP fork-join, shared/private, reductions)</span></span>
<span id="cb2-284"><a href="#cb2-284" aria-hidden="true" tabindex="-1"></a><span class="in">│   └── LeVeque: Ch 9 (2D diffusion stencils &amp; CFL stability limits)</span></span>
<span id="cb2-285"><a href="#cb2-285" aria-hidden="true" tabindex="-1"></a><span class="in">└── Week 6–7 (Midterm Quiz &amp; Problem Review)</span></span>
<span id="cb2-286"><a href="#cb2-286" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── Hager &amp; Wellein: Ch 1–3 (Dennard scaling, power wall, memory wall)</span></span>
<span id="cb2-287"><a href="#cb2-287" aria-hidden="true" tabindex="-1"></a><span class="in">    ├── King: Ch 11, 12, 17 (C pointers vs. Fortran column-major memory)</span></span>
<span id="cb2-288"><a href="#cb2-288" aria-hidden="true" tabindex="-1"></a><span class="in">    └── Course Archives: mid-prep-2026.html + 2025 Midterm solutions + progD57</span></span>
<span id="cb2-289"><a href="#cb2-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-290"><a href="#cb2-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-291"><a href="#cb2-291" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-292"><a href="#cb2-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-293"><a href="#cb2-293" aria-hidden="true" tabindex="-1"></a><span class="fu"># you asked</span></span>
<span id="cb2-294"><a href="#cb2-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-295"><a href="#cb2-295" aria-hidden="true" tabindex="-1"></a>message time: 2026-10-03 15<span class="sc">:05:</span>56</span>
<span id="cb2-296"><a href="#cb2-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-297"><a href="#cb2-297" aria-hidden="true" tabindex="-1"></a>now jsut give me what to read and in what order to read it</span>
<span id="cb2-298"><a href="#cb2-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-299"><a href="#cb2-299" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-300"><a href="#cb2-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-301"><a href="#cb2-301" aria-hidden="true" tabindex="-1"></a><span class="fu"># gemini response</span></span>
<span id="cb2-302"><a href="#cb2-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-303"><a href="#cb2-303" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 1: Systems, Shells, and Language Toolchains (Lectures 1–3)</span></span>
<span id="cb2-304"><a href="#cb2-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-305"><a href="#cb2-305" aria-hidden="true" tabindex="-1"></a>Read these foundational texts first to navigate the cluster environments (<span class="in">`art-1`</span> running CentOS with <span class="in">`tcsh`</span> and <span class="in">`art-16`</span> running Rocky Linux with <span class="in">`bash`</span>), configure remote access, and establish baseline C or Modern Fortran compilation pipelines:</span>
<span id="cb2-306"><a href="#cb2-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-307"><a href="#cb2-307" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Mark G. Sobell — *A Practical Guide to Linux Commands, Editors, and Shell Programming*** (or **Matthew — *Beginning Linux Programming*, Chapters 1–5**)</span>
<span id="cb2-308"><a href="#cb2-308" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Scope to read:** Shell navigation (<span class="in">`cd`</span>, <span class="in">`ls -la`</span>), process control (<span class="in">`ps`</span>, <span class="in">`bg`</span>, <span class="in">`fg`</span>, <span class="in">`kill`</span>, <span class="in">`&amp;`</span>), stream redirection (<span class="in">`&gt;`</span>, <span class="in">`&gt;&gt;`</span>, <span class="in">`|`</span>), and text editors (<span class="in">`vi`</span>/<span class="in">`vim`</span>, <span class="in">`nano`</span>, <span class="in">`micro`</span>).</span>
<span id="cb2-309"><a href="#cb2-309" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Shell differences:** Study the syntax variations between <span class="in">`bash`</span> (environment variables via <span class="in">`export VAR=value`</span>, aliases via <span class="in">`alias name='command'`</span>) and <span class="in">`tcsh`</span> (variables via <span class="in">`setenv VAR value`</span>, aliases via <span class="in">`alias name 'command'`</span>).</span>
<span id="cb2-310"><a href="#cb2-310" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Explicit exclusions:** Skip sections covering <span class="in">`sed`</span>, <span class="in">`awk`</span>, <span class="in">`perl`</span>, <span class="in">`emacs`</span>, SQL databases, semaphores, pipes/sockets, and low-level POSIX calls.</span>
<span id="cb2-311"><a href="#cb2-311" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Networking &amp; security:** Review remote connectivity commands (<span class="in">`ssh`</span>, <span class="in">`sftp`</span>, <span class="in">`traceroute`</span>, <span class="in">`ping`</span>) and securing server access via <span class="in">`/etc/hosts.deny`</span>.</span>
<span id="cb2-312"><a href="#cb2-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-313"><a href="#cb2-313" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Norbert Schörghofer — *Lessons in Scientific Computing***</span>
<span id="cb2-314"><a href="#cb2-314" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Chapter 1 (pp. 25–35):** Read the performance comparisons between compiled languages (C, Fortran 95) and interpreted environments (Python, NumPy, MATLAB, IDL), focusing on why inner loops require compiled binaries.</span>
<span id="cb2-315"><a href="#cb2-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-316"><a href="#cb2-316" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Language Foundations (Select Your Primary Language: C or Modern Fortran)**</span>
<span id="cb2-317"><a href="#cb2-317" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**If choosing C:**</span>
<span id="cb2-318"><a href="#cb2-318" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Stephen G. Kochan — *Programming in C* (Chapters 7–11)** or **Kernighan &amp; Ritchie (K&amp;R) — *The C Programming Language* (Chapters 1–5):** Focus on arrays, pointer arithmetic, memory addresses, and dynamic allocation via <span class="in">`malloc`</span> and <span class="in">`free`</span>.</span>
<span id="cb2-319"><a href="#cb2-319" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**K. N. King — *C Programming: A Modern Approach* (Chapters 11, 12, &amp; 17):** Study flattened 1D array indexing (<span class="in">`grid[i * N + j]`</span>) versus jagged pointer arrays (<span class="in">`grid[i][j]`</span>) to understand spatial cache locality.</span>
<span id="cb2-320"><a href="#cb2-320" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**If choosing Fortran:**</span>
<span id="cb2-321"><a href="#cb2-321" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Stephen J. Chapman — *Fortran for Scientists and Engineers* (Chapters 1–8)** (or **Brainerd / Chivers**): Study free-form source formatting, <span class="in">`implicit none`</span>, array operations, modules, and case-insensitivity rules.</span>
<span id="cb2-322"><a href="#cb2-322" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Milan Curcic — *Modern Fortran: Building Efficient Parallel Applications* (Chapters 2–5):** Focus on whole-array arithmetic, multidimensional array slices (<span class="in">`A(1:N:2)`</span>), and intrinsic array functions.</span>
<span id="cb2-323"><a href="#cb2-323" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**For Python Interoperability:**</span>
<span id="cb2-324"><a href="#cb2-324" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**J. Izaac &amp; J. B. Wang — *Computational Quantum Mechanics* (Chapters 2 &amp; 3):** Read Chapter 2 for Modern Fortran array foundations and Chapter 3 for scientific Python and wrapping compiled C/Fortran routines.</span>
<span id="cb2-325"><a href="#cb2-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-326"><a href="#cb2-326" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-327"><a href="#cb2-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-328"><a href="#cb2-328" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 2: Material for Assignment 1 (Due Lecture 4)</span></span>
<span id="cb2-329"><a href="#cb2-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-330"><a href="#cb2-330" aria-hidden="true" tabindex="-1"></a>Work through these readings to build the analytical physics formulations, asymptotic algorithmic proofs, and finite-difference stencils required for the four assignment problems:</span>
<span id="cb2-331"><a href="#cb2-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-332"><a href="#cb2-332" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 2A: Flight Dynamics and Aerobatic Loop Analysis (Problem 1.1)</span></span>
<span id="cb2-333"><a href="#cb2-333" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Robert Resnick, David Halliday, &amp; Kenneth S. Krane (RHK) — *Physics, Vol. 1* (5th Ed.)**</span>
<span id="cb2-334"><a href="#cb2-334" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 4 (§4.5):** Kinematics of relative velocity and constructing airspeed-wind drift vector triangles: $\mathbf{v}_{\text{ground}} = \mathbf{v}_{\text{plane}} + \mathbf{v}_{\text{wind}}$.</span>
<span id="cb2-335"><a href="#cb2-335" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapters 7 &amp; 8:** Work, kinetic energy, and mechanical energy conservation along vertical arcs: $v(y) = \sqrt{v_0^2 - 2gy}$.</span>
<span id="cb2-336"><a href="#cb2-336" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**John D. Anderson — *Introduction to Flight* (8th/9th Ed.)**</span>
<span id="cb2-337"><a href="#cb2-337" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 5 (§5.13–§5.15):** Normal load factor $n = 1 + v^2/(gR)$, centripetal pull-up force balance, and apex weightlessness determining the circular radius $R = v_0^2/(5g)$.</span>
<span id="cb2-338"><a href="#cb2-338" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 5 (§5.16):** The $V\text{–}n$ flight envelope and dynamic stall speed scaling $v_S(n) = v_{S,0}\sqrt{n}$.</span>
<span id="cb2-339"><a href="#cb2-339" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**John R. Taylor — *Classical Mechanics***</span>
<span id="cb2-340"><a href="#cb2-340" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapters 1 &amp; 2 (§2.1–§2.4):** Quadratic aerodynamic drag vectors $\mathbf{F}_D = -\frac{1}{2}\rho C_D A v \mathbf{v}$.</span>
<span id="cb2-341"><a href="#cb2-341" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 3 (§3.1–§3.3):** Momentum conservation and center-of-mass decoupling.</span>
<span id="cb2-342"><a href="#cb2-342" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Bernard Etkin &amp; Lloyd Duff Reid — *Dynamics of Flight: Stability and Control* (3rd Ed.)**</span>
<span id="cb2-343"><a href="#cb2-343" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 5 (§5.1–§5.6):** Coupled longitudinal equations of motion in speed $v(t)$ and flight-path angle $\theta(t)$, and load-dependent induced drag polar modeling: $C_D = C_{D0} + K C_L^2$.</span>
<span id="cb2-344"><a href="#cb2-344" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**William H. Press et al. — *Numerical Recipes* (3rd Ed.) / Mark Newman — *Computational Physics***</span>
<span id="cb2-345"><a href="#cb2-345" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Press et al., Chapter 16 (§16.1–§16.3)** or **Newman, Chapter 8 (§8.1–§8.4):** Explicit fourth-order Runge–Kutta (RK4) integration with adaptive step-size control and trajectory closure checks at $\theta = 2\pi$.</span>
<span id="cb2-346"><a href="#cb2-346" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Vladimir Arnold — *Mathematical Methods of Classical Mechanics* (2nd Ed.)**</span>
<span id="cb2-347"><a href="#cb2-347" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 3 (§12, §16):** Clothoid (Euler spiral) curvature parameterization $\kappa(s) = s/A^2$ to eliminate unbounded normal jerk ($\dot{n} \to \infty$).</span>
<span id="cb2-348"><a href="#cb2-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-349"><a href="#cb2-349" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 2B: Multiphase Air-Water Ballistics (Problem 1.2)</span></span>
<span id="cb2-350"><a href="#cb2-350" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**RHK — *Physics, Vol. 1* (5th Ed.)**</span>
<span id="cb2-351"><a href="#cb2-351" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 15 (§15.1–§15.4):** Fluid statics, hydrostatic pressure variation, Archimedes' buoyancy, and effective gravity in water: $g_{\text{eff}} = g(1 - \rho_w/\rho_p)$.</span>
<span id="cb2-352"><a href="#cb2-352" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**John R. Taylor — *Classical Mechanics***</span>
<span id="cb2-353"><a href="#cb2-353" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 2 (§2.1–§2.4):** Motion in resisting media and closed-form vertical terminal velocity $v_t = \sqrt{2m g_{\text{eff}} / (\rho C_D A)}$.</span>
<span id="cb2-354"><a href="#cb2-354" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Randall J. LeVeque — *Finite Difference Methods for Ordinary and Partial Differential Equations***</span>
<span id="cb2-355"><a href="#cb2-355" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapters 1–3:** Initial value problems across discontinuous interfaces and managing severe deceleration spikes across the air-water density boundary.</span>
<span id="cb2-356"><a href="#cb2-356" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Press et al. — *Numerical Recipes* (3rd Ed.)**</span>
<span id="cb2-357"><a href="#cb2-357" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 9 &amp; Chapter 16 (§16.6):** Brent’s root-finding method for detecting the interface impact zero-crossing $y(t^*)=0$ and managing stiff differential equations.</span>
<span id="cb2-358"><a href="#cb2-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-359"><a href="#cb2-359" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 2C: Vector Monotonicity and Memory Optimization (Problem 1.3)</span></span>
<span id="cb2-360"><a href="#cb2-360" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Thomas H. Cormen et al. (CLRS) — *Introduction to Algorithms* (3rd/4th Ed.)**</span>
<span id="cb2-361"><a href="#cb2-361" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 3 (§3.1–§3.2) &amp; Chapter 4 (§4.1):** Asymptotic growth notations ($\Theta, \mathcal{O}, \Omega$), algebraic proof that naive pairwise comparisons scale as $\sum_{i=1}^{N-1}(N-i) \in \Theta(N^2)$, and prefix reduction to a linear $\Theta(N)$ scan.</span>
<span id="cb2-362"><a href="#cb2-362" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Donald E. Knuth — *The Art of Computer Programming, Vol. 2: Seminumerical Algorithms***</span>
<span id="cb2-363"><a href="#cb2-363" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapters 3 &amp; 4:** Discrete sequence scanning, loop invariants, and proof of single-pass running minimum optimization requiring $\mathcal{O}(1)$ auxiliary storage.</span>
<span id="cb2-364"><a href="#cb2-364" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Randal E. Bryant &amp; David R. O'Hallaron — *Computer Systems: A Programmer's Perspective (CS:APP)* (3rd Ed.)**</span>
<span id="cb2-365"><a href="#cb2-365" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 5 (§5.7–§5.12):** Program optimization, instruction-level parallelism (ILP), and loop unrolling.</span>
<span id="cb2-366"><a href="#cb2-366" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 6 (§6.2–§6.6):** The memory hierarchy, 64-byte L1/L2/L3 cache lines, spatial locality, and avoiding cache misses during $N \sim 10^7$ element traversals.</span>
<span id="cb2-367"><a href="#cb2-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-368"><a href="#cb2-368" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 2D: Second-Derivative Stencil Truncation and Roundoff Limits (Problem 1.4)</span></span>
<span id="cb2-369"><a href="#cb2-369" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Randall J. LeVeque — *Finite Difference Methods***</span>
<span id="cb2-370"><a href="#cb2-370" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 1 (§1.1–§1.3):** Taylor series expansions and analytical derivation of the 3-point central difference truncation error bound: $E_{\text{trunc}} = \frac{h^2}{12}|f^{(4)}(\xi)|$.</span>
<span id="cb2-371"><a href="#cb2-371" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Mark Newman — *Computational Physics***</span>
<span id="cb2-372"><a href="#cb2-372" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 5 (§5.10):** Subtractive floating-point roundoff cancellation: $E_{\text{round}} = \frac{4\epsilon_{\text{mach}}}{h^2}|f|$, derivation of optimal step size $h_{\text{opt}} \sim \epsilon_{\text{mach}}^{1/4}$, and generating the log-log error V-curve.</span>
<span id="cb2-373"><a href="#cb2-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-374"><a href="#cb2-374" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-375"><a href="#cb2-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-376"><a href="#cb2-376" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 3: Material for Assignment 2 (Due Lecture 6)</span></span>
<span id="cb2-377"><a href="#cb2-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-378"><a href="#cb2-378" aria-hidden="true" tabindex="-1"></a>Read these sources to implement stochastic Monte Carlo simulations and shared-memory parallel programming:</span>
<span id="cb2-379"><a href="#cb2-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-380"><a href="#cb2-380" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 3A: Monte Carlo Integration and Error Scaling</span></span>
<span id="cb2-381"><a href="#cb2-381" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Mark Newman — *Computational Physics***</span>
<span id="cb2-382"><a href="#cb2-382" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 10 (§10.1):** Pseudo-random number generators, linear congruential generators (LCGs), random seeds, and uniform sampling.</span>
<span id="cb2-383"><a href="#cb2-383" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 10 (§10.2):** Monte Carlo integration methods, including hit-or-miss and mean-value estimation of $\pi$.</span>
<span id="cb2-384"><a href="#cb2-384" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 10 (§10.3):** Statistical errors, the Central Limit Theorem, and proof of the dimension-independent $\sigma \propto \frac{1}{\sqrt{N}}$ convergence rate.</span>
<span id="cb2-385"><a href="#cb2-385" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Press et al. — *Numerical Recipes* (3rd Ed.)**</span>
<span id="cb2-386"><a href="#cb2-386" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 7 (§7.1–§7.3):** Random number generation, period lengths, and eliminating LCG hyper-plane correlations.</span>
<span id="cb2-387"><a href="#cb2-387" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 15 (§15.1):** Statistical modeling, sample variance, and confidence intervals.</span>
<span id="cb2-388"><a href="#cb2-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-389"><a href="#cb2-389" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Step 3B: OpenMP Loop Parallelization and 2D Diffusion</span></span>
<span id="cb2-390"><a href="#cb2-390" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Georg Hager &amp; Gerhard Wellein — *Introduction to High Performance Computing for Scientists and Engineers***</span>
<span id="cb2-391"><a href="#cb2-391" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 6 (§6.1–§6.2):** The fork-join thread execution model and work-sharing loop constructs (<span class="in">`#pragma omp parallel for`</span> in C, <span class="in">`!$omp parallel do`</span> in Fortran).</span>
<span id="cb2-392"><a href="#cb2-392" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 6 (§6.3):** Data scoping rules, thread-safety, distinguishing <span class="in">`shared`</span> arrays from loop-private variables (<span class="in">`private`</span>, <span class="in">`firstprivate`</span>), and preventing data races.</span>
<span id="cb2-393"><a href="#cb2-393" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 6 (§6.4):** Reduction operations (<span class="in">`reduction(+:sum)`</span>) for accumulating multi-threaded Monte Carlo sums across CPU cores.</span>
<span id="cb2-394"><a href="#cb2-394" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Milan Curcic — *Modern Fortran: Building Efficient Parallel Applications***</span>
<span id="cb2-395"><a href="#cb2-395" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapters 11 &amp; 12:** Parallelizing loops with OpenMP directives, chunk scheduling (<span class="in">`schedule(static)`</span> vs. <span class="in">`schedule(dynamic)`</span>), and SIMD compiler auto-vectorization.</span>
<span id="cb2-396"><a href="#cb2-396" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Randall J. LeVeque — *Finite Difference Methods***</span>
<span id="cb2-397"><a href="#cb2-397" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>**Chapter 9:** Parabolic PDEs and explicit 2D 5-point Laplace stencil updates for the diffusion equation:</span>
<span id="cb2-398"><a href="#cb2-398" aria-hidden="true" tabindex="-1"></a>    $$u_{i,j}^{n+1} = u_{i,j}^n + \Delta t \left( \frac{u_{i+1,j}^n - 2u_{i,j}^n + u_{i-1,j}^n}{\Delta x^2} + \frac{u_{i,j+1}^n - 2u_{i,j}^n + u_{i,j-1}^n}{\Delta y^2} \right)$$</span>
<span id="cb2-399"><a href="#cb2-399" aria-hidden="true" tabindex="-1"></a>    Managing grid boundary updates in parallel and verifying the numerical CFL stability limit: $\Delta t \le \frac{\Delta x^2}{4D}$.</span>
<span id="cb2-400"><a href="#cb2-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-401"><a href="#cb2-401" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb2-402"><a href="#cb2-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-403"><a href="#cb2-403" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 4: Midterm Exam Preparation (Lecture 7)</span></span>
<span id="cb2-404"><a href="#cb2-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-405"><a href="#cb2-405" aria-hidden="true" tabindex="-1"></a>The midterm exam is split into an 8% theoretical quiz and an 8% written problem-solving section (allowing 8 handwritten note pages / 4 double-sided sheets and a calculator). Complete these readings and code inspections in order:</span>
<span id="cb2-406"><a href="#cb2-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-407"><a href="#cb2-407" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Hardware Architecture, Microprocessors, and Physical Bottlenecks (Quiz Scope)**</span>
<span id="cb2-408"><a href="#cb2-408" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Paul E. Ceruzzi — *A History of Modern Computing* (Chapters 5 &amp; 6):** Microprocessor development, Intel x86 architecture, the origins of Unix and Linux, and the growth of the Internet.</span>
<span id="cb2-409"><a href="#cb2-409" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Georg Hager &amp; Gerhard Wellein — *Introduction to High Performance Computing*:**</span>
<span id="cb2-410"><a href="#cb2-410" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Chapter 1:** Superscalar pipelines, clock frequency ceilings, and SIMD instruction registers.</span>
<span id="cb2-411"><a href="#cb2-411" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Chapter 2 (§2.1–§2.3):** Arithmetic intensity (FLOPs per byte of DRAM transfer), cache line latency, and the memory bandwidth wall.</span>
<span id="cb2-412"><a href="#cb2-412" aria-hidden="true" tabindex="-1"></a><span class="ss">     * </span>**Chapter 3:** The breakdown of Dennard scaling around 2004–2005 due to leakage currents, the processor power wall, the shift to multi-core architectures, and the sustainability of Moore's Law.</span>
<span id="cb2-413"><a href="#cb2-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-414"><a href="#cb2-414" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Memory Models and Language Standards (Quiz &amp; Problem Scope)**</span>
<span id="cb2-415"><a href="#cb2-415" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**K. N. King — *C Programming: A Modern Approach* (Chapters 11, 12, 17):** Contrast C row-major (lexicographical) contiguous buffer storage with Fortran column-major storage, and analyze why non-contiguous memory layouts degrade hardware prefetching.</span>
<span id="cb2-416"><a href="#cb2-416" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Compiler Toolchains &amp; Flags:** Review GCC (<span class="in">`gcc`</span>, <span class="in">`gfortran`</span>), Intel (<span class="in">`icc`</span>, <span class="in">`ifort`</span>, <span class="in">`ifx`</span>), and NVIDIA (<span class="in">`nvcc`</span>, <span class="in">`nvfortran`</span>) compiler optimization flags (<span class="in">`-O2`</span>, <span class="in">`-O3`</span>, <span class="in">`-fopenmp`</span>, <span class="in">`-march=native`</span>).</span>
<span id="cb2-417"><a href="#cb2-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-418"><a href="#cb2-418" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Algorithmic Puzzles and Instructor Code Repository (`progD57`)**</span>
<span id="cb2-419"><a href="#cb2-419" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**The 711 Numerical Puzzle (Lecture 4):** Review the prime factorization of $711 \times 10^6 = 2^6 \cdot 3^2 \cdot 5^6 \cdot 79$ and how constraint pruning (isolating multiples of 79 with ordered loops $a \le b \le c \le d$) eliminates brute-force $\mathcal{O}(N^4)$ search costs.</span>
<span id="cb2-420"><a href="#cb2-420" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Kruskal Counts &amp; Linked Lists (Lecture 4):** Trace how deterministic hopping over card sequences maps directly to linked-list node chains in C pointers and Fortran array indices.</span>
<span id="cb2-421"><a href="#cb2-421" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Live Code Inspection:** Download, compile, and run the professor's sample codes at <span class="in">`[http://planets.utsc.utoronto.ca/~pawel/progD57](http://planets.utsc.utoronto.ca/~pawel/progD57)`</span> for the 711 puzzle, Kruskal counts, OpenMP Monte Carlo $\pi$ calculations, and the parallel 2D diffusion stencil.</span>
<span id="cb2-422"><a href="#cb2-422" aria-hidden="true" tabindex="-1"></a><span class="ss">   * </span>**Exam Archives:** Review `mid-prep-2026.html` and the 2025 Midterm Exam solutions, paying close attention to quiz traps where incorrect technical terms are enclosed in quadruple asterisks (`****word****`).</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Igor Kan</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>