---
title: "PHYD57 Course Information & Literature Portal"
subtitle: "Advanced Computational Methods in Physics — Official Webpage Text & Resources"
date: "2026-09-10"
categories: ["Syllabus", "Course Administration", "HPC"]
draft: true
format:
  html:
    toc: true
    toc-depth: 3
---

# Course PHYD57. Advanced Computational Methods in Physics

Welcome to the course that will help you become a more knowledgeable and better scientific programmer! You already know basic programming in Python (cf. next section). Now is the time to learn some history and even some physics behind our technical civilization, where computing is helping us everywhere. Powerful operating system (linux) and languages will be discussed and tried out, networking, and the principles of parallel programming that enables you as a scientist to run large-scale simulations of the physical world. We will also discuss some advanced algorithms used in Physics. The course includes practical exercises in writing and optimizing programs on single node(s) of a computational cluster. Although we'll outline the methods, we leave out the node-to-node communication and writing message-passing programs. You can acquire those skills later, as part of a research undergrad or a grad course.

---

## Brief Intro

### 2025 Syllabus
TXT file with dates of lectures and exams, topics

### Quercus
This page provides the sole access to all the materials, up-to-date SYLLABUS (any changes in schedule will be seen there), texts of assignments, and preliminary grades. The present page will be modified with new contents as the course progresses. Things highlighted in red are newly added or important in the near future.  
Quercus will be used for: submission of your term work, announcements via email, and posting of recordings in Media Gallery (old ones - because our classroom does not have the AURA equipment to record our meetings).

---

## Prerequisites
The only crucial prerequisite is programming using basic Python at the level of PHYB57, Introduction to Computing in Physics. If you are rusty in Python, refresh your practical skills a.s.a.p. - solve a pendulum problem, two weakly coupled pendula, or something else.. include a comparison with an analytical solution in the code.

---

## Languages
This course assumes you are interested in:
1. Intermediate and advanced numerical methods used in physical sciences;
2. HPC (High Performance Computing), including parallelization of algorithms;
3. Coding in one of the HPC languages more powerful than Python.

After this course you will understand programs (with their arithmetic, iterations/loops, conditional statements, functions/subroutines and their calling, array declaration and usage, pseudorandom numbers, and so on) in both C and Fortran. You will be required to actively express your ideas (a more demanding task) in one of those languages, you choose which one. In other words, we want you to acquire passive knowledge of C(++) AND modern Fortran, and active knowledge of C(++) OR Fortran.

The pros and cons of C vs. Fortran will be discussed in the first meetings, but here is a brief take. By Fortran we mean modern fortran: 90, 95, 2003, 2008, or 2015 definitions; they are actually almost the same for our purposes. Avoid books/tutorials on really old, earlier FORTRAN versions (IV, 77), even though Fortran, unlike Python, is virtually backward compatible. Knowing Python, Fortran is easier to learn/use than C++. It has changed much since its inception long time ago, but one thing remained constant. From supercomputers to laptops, scientific simulations in Fortran (typically using multidimensional arrays) are among the fastest-executing. Which may be a surprise, because literally thousands of languages have been invented since Fortran. But very few with advanced physical computations in mind!

C(++) is also old, though a few decades younger, and different: more wordy, with more bells and whistles, it is lower level (we'll discuss what that means). It is better known and thus more marketable outside academia. C is a sine qua non for operating system writers, guardians and hackers. Many programmers are not happy with C++ (see the section with links on HPC languages below). Scientists have a love/hate relationship with C++; even though they weren't originally meant for each other, they've been together for ages and gave birth to many great implementations and program packages.

Intel and Nvidia are providing both C and Fortran in their separate, powerful compiler suites for free. And there are open-projects such as gcc and gfortran (every linux, macos & other OS has C/C++ compiler named gcc installed; g stands for GNU, which is an inside joke (ask your AI friend what GNU means).

---

## Course Grading Scheme
* **3 sets of assignments A1-A3:** 21% (7% ea.)
* **group project (assignment A4):** 23%
* **midterm exam:** 16% (8% Probl + 8% Quiz)
* **final exam:** 40% (23% Probl + 17% Quiz)

---

## Lectures, Tutorials, Office Hours, UofT Code of Conduct, etc.
**Lectures** (see syllabus for dates and times) follow the organization outlined in syllabus & are in-person. You are expected to take own notes of what's happening on the blackboard, while this page will serve the pdf's of on-screen presentations (slides). Media gallery on Quercus will have old recordings for optional use. Informative pages or animations direct from the web sometimes appear during lectures as well; it's a good practice to note down some keywords or their URLs, for visiting them later.

**Tutorials** are NOT meant for the explanation of Lectures, even though occasionally they do so. There will be no cookie points for attendance/activity. Negative aspects of not attending and not being active will be automatic and obvious enough. We are a small bunch of people interested in HPC; it makes the course de facto a bit like a graduate course.

**Office hours:** let's discuss things immediately after the tutorial. I'll try to stay until all topics you want to talk about are discussed or until I have to leave. We will see where we can talk, if our classroom is busy we'll move to one of the rooms on 5th floor (SW). Other times may be arranged on Thursdays.

**The Code of Behaviour on Academic Matters at UofT should be respected.** If you have not read it, you may unknowingly find yourself in trouble. This document succinctly defines conduct that constitutes plagiarism, i.e. misrepresentation of authorship, e.g., cheating that the assigned work is yours and original, while you merely rephrase somebody's code by changing its appearance. It is an equal offense to help somebody plagiarize your own work. The Code mentions how any reasonably grounded suspicions must be addressed by your Instructor, by Dept. Chair, and so on. Of course a group work on assignment 4 a different matter. So please read more here.

Last but not least, **using generative AI to plagiarize solutions of an assignment or test is a serious offense. Do not use it, unless it's clearly stated as needed in the text of the assignment.**

You may want to explore this link to see some of the problematic aspects of "AI". Or spot at least 10 impossible things in this seemingly OK poster (AI-generated). The role of such software in today's world, in education, and your own future, are of course all interesting issues, which we may discuss during the breaks, but that's not really a subject of PHYD57. Having said that, you must understand how neural nets (NN) work, so toward the end of the course you will see examples of NN-based machine learning; you may also study ML more deeply yourself in your group project.

---

## Contact
Email or visit the instructor **Prof. Pawel Artymowicz** (guide to pronunciation: w=v, cz=ch, so: PAvel ArtyMOvich), in SW 506G, on the 5th floor (Physics & Astrophysics) in old Science Wing. Email: `pawel.artymowicz@utoronto.ca`, importantly with a subject line `"PHYD57"`, or else it may be accidentally ignored. Please send mail from your utor account, not gmail, hotmail etc.

Tutorials are given by the lecturer. This course's TA/marker is .... [email: `firstname.lastname@mail.utoronto.ca`]. Please contact TA with questions, difficulties, or about the grading. If needed, the TA will transfer the matter to me.

---

## Course Contents & HPC Environment
You have learned how to program (in PHYB57) and saw some basic numerical methods. Now it's time for more algorithms and techniques, used in numerical physics. You will discover the world of High Performance Computing (HPC): how and why it emerged in the history of computing. You will get to understand two HPC languages.

Practical skills will include a basic familiarity with the Linux operating system. If not familiar with it, you may want to read about it on the net even before the course starts. You are encouraged but not required to install some linux (Rocky, Red Hat, Fedora, Ubuntu, Mint or other flavor of Linux) on your computer (or use MacOS, which is basically Linux customized by Apple).

You will have access to one node of a cluster housed in BV building (there is a banner with a photo of the art cluster next to the entrance to DPES office in EV bldg). It has Centos 6 flavor of linux and the basic software, enough for doing exercises on your own remotely.  
Physical access to the server room is restricted, even I don't have the codes and the key, so if the machine(s) crash because of something (e.g. power outage) then we are temporarily in trouble. Therefore you'll backup your work on your machine, and I will try to remember to do the same. As a disclaimer, making the research machine(s) available to you is outside the scope of u/g courses and is an extra benefit to you given by me without explicit or implicit promises. You should try to develop and debug codes (and run them) on your own machine, which is quite feasible.

On your computer, you will sometimes use your Python3, and will be asked to install compiler(s) for HPC languages Fortran and/or C(++), and familiarize yourself with how they function. (If you already know both these languages, which of course would be quite a surprise, then please try to install the Julia compiler and try that new language, if you can call that a language created while most of you were beginning to read. Julia was born at MIT, for purposes consistent with ours. Sharing your experience will be appreciated - we'll think of exactly how once we get to that point.)

In summary, our goals are to help you become a better scientific programmer, able to solve numerically demanding problems on a workstation or a good laptop. While the practice of cluster supercomputing is outside the scope of this undergraduate course, you will hear a lot about it, and even have an option to try it small-scale if you want.

This is a 4th year (upper u/g) course. It explains the issues, tries to interest you in some directions and put you on the right track, but it's your job to move along. This means your own initiative in learning is expected. Lots of materials, books, web pages, will be suggested to you, and often you will make your own choice which of them to pursue closer. Start very soon. Happy experimenting with the kind of computing you likely haven't experienced yet.

---

## Assignments & Emergency Accommodations
The deadline is at the beginning of the meeting (11 am) on lecture days marked in syllabus. Submission format is explained in the text of assignment 1. Submission late by more than 3 hr earns 50% of points. There are no extensions. This policy is motivated both by the need to discuss/publish solutions a.s.a.p. in the tutorial, and basic fairness to those who respect deadlines.

### Accommodation for emergencies (assig's and midterm):
Transfer of points for personal or medical emergencies is offered, following the UofT rules of self-declaration on ACORN (maximum one per term; can cover multiple courses for up to 7 days). Please send me a medical note (Verification of Illness Form, VOI) or self-declaration for the 1st absence, and VOI for any further or longer absences. Do not use questionable medical notes (there are doctors who will issue them for a fee, without seeing a student personally).

If you skip more than 1/2 of term work using VOIs, I will not grant further accommodations - you will be advised to drop the course before academic penalty deadline, since (i) this is an in-person, interactive course, and (ii) there is no historic precedent of someone missing most of the term work but writing successfully a final exam. Should there be a need for a deadline extension, it will apply to all of you, and be announced.  
For ways to file the self-declared absence please see this page. Please also forward the documents to me; sending them only to DPES may not assure fast delivery.

* **Text of assignment set #1. Due 2 Oct.** [Solutions](http://planets.utsc.utoronto.ca/~pawel/PHYD57/)
* **Text of assignment set #2. Due 16 Oct.** [Solutions of A2](http://planets.utsc.utoronto.ca/~pawel/PHYD57/)
* **Text of assignment set #3 (re-worded). Due 20 Nov.** [Solutions of A3](http://planets.utsc.utoronto.ca/~pawel/PHYD57/)
* **Assignment set #4. Group research project.** Presentation on 4 Dec.

---

## The Code Page
Continuously updated codes discussed in lectures or just worth knowing:  
<http://planets.utsc.utoronto.ca/~pawel/progD57>

You will download and run the codes. At first, before you gather the experience in compiling and running some of them, you can just take a look at them. As a registered PHYD57 student you are free to copy & develop the programs to do more things, change their output style, etc. That is how programmers learn programming. Only you have the right to do that - please don't share the link to this code page with the rest of the world.

Knowledge of basic structures and methods used in these codes is a course requirement. You must acquire a passive knowledge (i.e., ability to understand) of both the basic C and Fortran. You may actively program your assignments in one chosen language, C or C++ or Fortran, unless the particular assignment explicitly asks for Python script.

* **Volcano on Io:** Outputs Dislin graphics directly from this source code in F90: `volcano-disl.f90`

---

## Books & Literature
Please see the guide to literature in the lecture notes section below. Add a secret ingredient to the end of the URL you are viewing (`/refs/`), to see a helpful web page.

Books discussed below should be in UofT library, in electronic form. If not, let me know. Find books in the library catalog. I do not recommend only watching videos on YouTube about programming; most of them are only very remotely relevant to PHYD57. Our textbooks and materials will be shown in Lecture notes, and will be specific to the current lecture. For instance, 2nd or 3rd lecture will benefit from your reading the parts of:

1. **N. Schroeghofer, "Lessons in Scientific Computing", CRC 2019.**  
   Please focus on subjects not discussed in introductory course PHYB57, for instance author's views on different programming languages and how to select the best combination of two complementary ones. If you read a chapter and the contents seems really familiar, skip and begin the next chapter. [PDF Link](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Schoerghofer-Lessons.pdf)

2. **J. Izaac and J. Wang, "Computational Quantum Mechanics", Springer 2018.** [PDF Link](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Izaac-Computational_QM-2019.pdf)

3. **P. Turner, T. Arildsen, K. Kavanagh, "Applied Scientific Computing with Python", Springer 2018.** [PDF Link](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Turner-Applied_Sci_Computing_Python-.pdf)  
   Make sure all the subjects are known to you, even if not in great detail.

4. **Non-required book for those who want to brush up on Python:**  
   S. Linge, H. Langtangen, "Programming for Computations - Python", Springer 2019 [2nd edition uses Python3] [PDF Link](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Linge-Programming_for_Computations.pdf)

---

## Lecture Notes and Guides
Programs discussed in lecture notes are available from <http://planets.utsc.utoronto.ca/~pawel/progD57>  
Guide to literature L1-L5, approximately:

* [Lecture 1](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L1-D57-2025.pdf) · [Lecture 2](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L2-D57-2025.pdf) · [Lecture 3](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L3-D57-2025.pdf) · [Lecture 4](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L4-D57-2025.pdf)
* [Lecture 5](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L5-D57-2025.pdf) · [Lecture 6](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L6-D57-2025.pdf) · [Lecture 7](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L7-D57-2025.pdf) · [Lecture 8](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L8-D57-2025.pdf)
* [Lecture 9](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L9-D57-2025.pdf) · [Lecture 10](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L10-D57-2025.pdf) · [Lecture 11](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L11-D57-2025.pdf) · [Lecture 12](http://planets.utsc.utoronto.ca/~pawel/PHYD57/L12-D57-2025.pdf)

Two papers recommended for Neural Networks in application to Astronomy:  
* [NNs-spect.pdf](http://planets.utsc.utoronto.ca/~pawel/PHYD57/NNs-spect.pdf)
* [NN-exoplanets.pdf](http://planets.utsc.utoronto.ca/~pawel/PHYD57/NN-exoplanets.pdf)  
*(Also, look at the NN section of the private, auxiliary page!)*

---

## Midterm Exam
* This page: `mid-prep-2026.html` will help you prepare for midterm exam.
* [2025 Midterm with Quiz solutions](http://planets.utsc.utoronto.ca/~pawel/PHYD57/midtermD57-2025-sol.pdf). Wrong words (non-unique set!) are between quadruple asterisks.

---

## Group Project (A4)
All the descriptions are or will be published in the assignment 4 well ahead of the due date. For orientation, here are some suggested topics:
* Machine Learning from very noisy data: econophysics, algorithmic trading etc.
* What happens to an airliner after it loses a part of the wing: panel simulation of ideal aerodynamics
* Planetary system dynamics and stability: The Trappist-1 system.
* SPH: Particle simulation of fluid dynamics on CPU or Intel Xeon Phi, in application to either: a planet exciting density waves, turbulent jet, gas streams feeding a young binary star, or an airplane wing.
* N-body simulation of collapsing galaxy with massive black holes, using FFT gravity solver on GPU
* Structural dynamics: build a virtual Golden Gate bridge, study its deformation under dynamically applied loads
* Speech enhancement: can one make noisy recordings more understandable?
* Simulation of phase transitions in spin lattice (computational thermodynamics)
* Mie theory of scattering with application to glories and specters
* Your group's proposal (to be approved by the lecturer)

---

## Final Exam
The exam in 2026 will be 40% of course mark: 23% of that for problems, 17% for the quiz.

You will write a 3-hr final exam in person. It will consist of a computer-free first part (quiz + written problems in the booklet), taking about 1.5 hours. You will have some leeway in adjusting the length of that part individually, but not beyond the range of 1.25-1.75 hrs.

The second part requires computing. Please MAKE PRIOR ARRANGEMENTS to bring a computer (laptop or tablet) that will assist you with the following: (i) edit text files (programs), (ii) compile & run programs in C(++) or Fortran (your choice) or connect via command-line interface (e.g. ssh or puTTY) to art-1 or art-2 linux servers to do that remotely, (iii) submit files with your results to Quercus. For the first part of the exam, please also bring a calculator.

Use of any remote help (browser, "AI", phone) during the exam(s) is forbidden.

The tasks will not require doing graphics straight out of C/F. Practical knowledge of multithreading by OMP (OpenMP) and the ability to input/output data to a file will be assumed. Writing simple kernels in CUDA is required. Writing a code that you cannot successfully debug and run during the exam will earn partial credit, so don't hesitate to explain the difficulties and submit imperfect programs (we may make remarks but will not correct them while grading).

In addition to written problems, there will be a midterm-style Quiz (with approx. 50 questions). Please carefully review all the lecture notes. As in the midterm, you are allowed to use your own handwritten notes. The limit is 8 pages, either single or double-sided (4 sheets in the latter case).

It is not known yet if you will need to have a working Python on your computer for the possible task of plotting of functions representing your results (after inputting them from a text file produced by C/F program; you may submit screenshots of your computer's screen or .png/.jpg files). We will announce that a few weeks before exam. But it is useful to have a working Python anyway!  
Your exam may be submitted in one or in several files: the source codes you create may be in file(s) separate from the text of description of solutions, and any graphics files/screenshots).

### Further Hints About the Final Exam:
The exam will have 4 written problems, one or two analytical ones (in part 1 of exam). One or two problems will be numerical; you will create a code (detailed comments inside the code required!) & run it. Include the code output in a text file or PDF, which discusses methods of solution, implementation, and results. Unless you have a way to nicely paste the code into the results file, separately upload to Quercus the code file and results.

The tasks may deal with the numerical dynamics of some simple physical system, or may deal with the numerical calculus, convolution, PDEs, or optimization methods.  
There will be no complicated datasets given as input. Knowledge of how to write a simple CUDA kernel or OMP directives for parallelization may be a part of the required solution.

Description of all important steps of your algorithm should be placed inside the code as brief comment lines, and a longer description of the algorithm and/or implementation, in a separate file in .pdf, .docx or plain text format (it would be convenient to have one such file uploaded to Quercus for all the problems, but it's up to you).

When you modify or create codes, give them files names including problem number and the last 3 digits of your student number, please. Strangely, Quercus does not show the student numbers.) As you know from the assignments, infinite updates are allowed, in case you need them - but indicate in the name that it's an update, for instance by including the version number.

---

## Results
Please see the current tally: [resPHYD57-2026.txt](http://planets.utsc.utoronto.ca/~pawel/PHYD57/resPHYD57-2026.txt)

---

## Links & Guides

### Advice for Windows Users
Please see this advice on linux emulation provided by Daniel: [advice1.txt](http://planets.utsc.utoronto.ca/~pawel/PHYD57/advice1.txt)  
If you can't install Linux on your machine, do install compilers on Windows and use them in command window. It is good to have 2 different compilers. This, among others, will help you understand error messages better.

### History of Computing
* <http://www.linfo.org/bit.html> . A bit of a history of bit (b). Please study it, and follow links to other important basic concepts in that short article, which you will be required to understand and define during exams and quizzes, such as: bitrate, bandwidth, data bus, 32- vs. 64-bit systems, ASCII code, pixels, various powers of 10 in computer lingo, and RAM memory.
* <http://www.linfo.org/byte.html> . A byte of a history of Byte (B). Another bunch of important basic terminology.
* <https://en.wikipedia.org/wiki/Marian_Rejewski> . Marian Rejewski and ENIGMA decoding.
* <https://en.wikipedia.org/wiki/Bomba_(cryptography)> . Cryptographic bomb (Bomba).
* The Turing team & British Enigma-cracking effort; Thomas Flowers and Colossus.
* <http://mason.gmu.edu/~montecin/computer-hist-web.htm> Computing history
* <https://cs.uwaterloo.ca/~shallit/Courses/134/history.html> Computer science history, with further links.

### Supercomputers
* <https://www.top500.org> Supercomputing statistics and performance trends.
* <https://www.top500.org/list/2025/11/> Top 500 fastest supercomputers.
* [Exascale Ambitions](https://www.scientific-computing.com/feature/exascale-ambitions) Fugaku supercomputer and exaflop computing.

### Python Resources
* <https://wiki.python.org/moin/BeginnersGuide/Programmers> Python beginner guide.
* <https://docs.python.org/3.0/reference> Python Language Reference.
* <https://docs.python.org/3.0/reference/index.html> Python Documentation.
* <https://matplotlib.org/3.1.0/tutorials/introductory/pyplot.html> Matplotlib & Pyplot.
* <https://docs.scipy.org/doc/numpy/index.html> NumPy user guide.

### Linux, Flavours and Shells
* Accounts on `art-1` (CentOS 6.6) and `art-16` (Rocky 9.6).
* [Centos 6 tutorials](https://www.youtube.com/playlist?list=PLxl6w8_DOOLsyk7ZokhJVO7XiJvtfg2f5)
* [Rocky 9 tutorials](https://www.youtube.com/playlist?list=PLB-l-Ezt_uPqn0l1FSINlCgOwLwiNPUl7)
* <https://www.freecodecamp.org/news/the-best-linux-tutorials/>
* <http://www.linfo.org> Linux Information Project.
* <http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html#toc7> Bash Programming.
* <https://docs.freebsd.org/44doc/usd/04.csh/paper.html> Csh Shell Programming.
* <https://www.wisdomjobs.com/e-university/shell-scripting-tutorial-174.html> Shell scripting in different shells.

### Programming Languages (C/C++ vs. Fortran vs. Julia)
* <http://planets.utsc.utoronto.ca/~pawel/PHYD57/refs/> Primary reference page.
* <https://www.youtube.com/watch?v=7fGB-hjc2Gc> "The worst programming language of all time" (C++ critique).
* [Scientific Computing's Future](https://arstechnica.com/science/2014/05/scientific-computings-future-can-any-coding-language-top-a-1950s-behemoth/) Why Fortran stays fast.
* <https://flow.byu.edu/posts/sci-prog-lang> Andrew Ning's perspective on scientific programming languages.
* <https://docs.julialang.org/en/v1/> Julia Language.
* <https://www.learn-c.org> Interactive C Tutorial.
* <https://beginnersbook.com/2014/01/c-tutorial-for-beginners-with-examples/> C Tutorial with examples.
* <https://pages.mtu.edu/~shene/COURSES/cs201/NOTES/fortran.html> Fortran tutorial.
* <https://www.youtube.com/watch?v=vcFBwt1nu2U> Just for fun: BS programming language.

### Networking
* <https://www.youtube.com/playlist?list=PLQVJk9oC5JKp_8F9LPa3Pv67boA80KLm1> 14-part series on networking.

### Parallel Computing: OpenMP
* [Hands-on intro to OpenMP (SC08 slide show)](https://www.openmp.org/wp-content/uploads/omp-hands-on-SC08.pdf)
* [OMP: Introduction](http://jakascorner.com/blog/2016/04/omp-introduction.html)
* [OMP: for loops](http://jakascorner.com/blog/2016/05/omp-for.html)
* [OMP: Sections](http://jakascorner.com/blog/2016/05/omp-sections.html)
* [OMP: for loop scheduling](http://jakascorner.com/blog/2016/06/omp-for-scheduling.html)
* [OMP: Reduction](http://jakascorner.com/blog/2016/06/omp-for-reduction.html)
* [OpenMP 4.5 manual & examples](https://www.openmp.org/wp-content/uploads/openmp-4.5.pdf)
* [Performance Obstacles in threading using OpenMP](https://software.intel.com/en-us/articles/performance-obstacles-for-threading-how-do-they-affect-openmp-code)

### Parallel Computing: CUDA C and CUDA Fortran
* [CUDA Fortran blog by Greg Ruetsch](https://devblogs.nvidia.com/easy-introduction-cuda-fortran/)
* [CUDA C blog by Mark Harris](https://devblogs.nvidia.com/even-easier-introduction-cuda/)
* [CUDA C Presentation by Cyril Zeller](http://www.int.washington.edu/PROGRAMS/12-2c/week3/clark_01.pdf)
* [CUDA C Programming Guide (NVIDIA)](http://planets.utsc.utoronto.ca/~pawel/PHYD57/CUDA_C_Programming_Guide.pdf)
* [CUFFT Library Description](http://planets.utsc.utoronto.ca/~pawel/PHYD57/CUFFT_Library.pdf)
* [CUDA NVCC Compiler Manual](http://planets.utsc.utoronto.ca/~pawel/PHYD57/CUDA_Compiler_Driver_NVCC.pdf)
* [CUDA Fortran & C vs CPU Performance Paper](http://planets.utsc.utoronto.ca/~pawel/PHYD57/CUDA_Fortran_paper.pdf)
* [Dr. Dobbs CUDA Series](https://www.drdobbs.com/parallel/cuda-supercomputing-for-the-masses-part/207200659)
* [CUDA Fortran Compiler PGI v18 User Guide](http://planets.utsc.utoronto.ca/~pawel/PHYD57/pgi18cudaforug.pdf)
* [Fortran Compiler PGI v18 User Guide](http://planets.utsc.utoronto.ca/~pawel/PHYD57/pgi18ug-x86.pdf)
* [GPU Program using CUDA: tetraDg-3.f95](http://planets.utsc.utoronto.ca/~pawel/progD57/tetraDg-3.f95)

---

# 2026 SYLLABUS for course PHYD57

**Advanced Computational Methods in Physics**  
*last modified: Aug. 2026*

**Lecturer:** Prof. Pawel Artymowicz (`pawel.artymowicz@utoronto.ca`; please put PHYD57 in the subject line otherwise mail may be misplaced. Please use your mail.utoronto.ca account, not gmail! My answers to gmail often get lost. Expect that the answer may come from yahoo.com due to temporary troubles with sending mail from planets server, incoming mail not affected.)

________________________________________________________________________________

Lectures (L1..L12, 2 hrs with a break) are immediately followed by 1 hr tutorial (T1..T10). We meet in HLB108 on Fridays, 11:00 to 14:00.  
Deadlines for sets of assignments/projects, denoted A1-A4, are at 11 am.  
Assignments are posted >= 7 days before they are due.

| Date | Event | Comments |
| :--- | :--- | :--- |
| **September 11** | L1, T1 | |
| **September 18** | L2z | L2 is synchron. online (on zoom) |
| **September 25** | L3, T2 | |
| **October 2** | L4, T3, **A1** | |
| **October 9** | L5, T4 | |
| **October 16** | L6, T5, **A2** | please form groups for A4 by this date |
| **October 23** | L7, T6 | **<--- midterm in class (11:10-12:10)** |
| **October 30** | -- | *(reading week)* |
| **November 6** | L8, T7 | |
| **November 13** | L9, T8 | |
| **November 20** | L10, **A3** | |
| **November 27** | L11, T9 | |
| **December 4** | L12, T10, **A4** | Group project presentations |
| **December ??** | **Final\*** | 3-hr final exam |

```
*) - 3hr final exam in person. It will consist of a computer-free first part 
(quiz + written problems in the booklet), taking about 1.5 hrs, and the 2nd
part that requires computing. Please MAKE PRIOR ARRANGEMENTS to bring a 
computer (laptop, tablet) that will assist you with the following: 
(i) edit text files (programs), 
(ii) compile & run programs in C(++) or Fortran (your choice) or connect via
command-line interface like ssh or puTTY to art-1 or art-2 linux server,
to do that remotely, 
(iii) submit files with your results to Quercus.
For the first part of the exam, please also bring a calculator. Use of any 
remote help (www browser, "AI" etc.) during the exam(s) is forbidden.
```

---

## Detailed Contents of the Course
*(will evolve slightly. Please re-download this file weekly.)*

### 1. Structure and scope of the course
* Syllabus of PHYD57
* Numerical Comp. in Physical Sciences: History and Contemporary efforts

### 2. HPC: need for speed, why and how
* History and modernity: microprocessors, Unix, Linux, and Internet
* Intro to Linux (CentOS)
* Command line interface and shells (bash and tcsh)
* Text editors: vi, nano, gedit, micro

### 3. Connectivity (ssh & sftp, traceroute & ping)
* Securing the linux system against break-ins via `/etc/hosts.deny`
* Basic Linux shells and commands (`bash`, `tcsh`, `cd`, `ls`, `ps`, `&`, `bg`, `fg`, `alias`, `export`/`setenv`, `rm`, output redirection to file via `>`)
* Getting more info: manual pages (`man`), `-h`, `--help`, or `-help` modifiers
* Recommended compilers: GNU (`gcc`, `gfortran`), Intel (`icc`, `ifort` or `ifx`), Nvidia (`nvcc`/`nvc++`, `nvfortran` formerly `pgf95`)
* Simple program in C, Fortran95, Python, Matlab, IDL (Schoerghofer, p. 30)
* More complex program, example of HPC: 2nd order Laplace operator stencil for the diffusion equation
* Speed comparison of C/F95 with Python & Numpy: why we learn HPC

### 4. C and Fortran 95 - compilers, basic usage
* Numerical puzzle of 711 - learning C and Fortran
* Kruskal counts and their connection to linked lists
* Coding Kruskal counts trick in Python and Fortran
* C: Language overview, compilers
* Integration with Python: calling C from Python
* Examples of programs

### 5. Discussion of the solutions of A2 assignment set
* More Fortran. Monte Carlo method (MtC)
* Examples of programs: Random numbers and MtC (finding $\pi$)
* Slow convergence: const./$\sqrt{N}$ scaling of error in MtC
* Parallel execution on CPU using OpenMP fork-join method in loops
* Parallel implementations: in-depth diffusion equation

### 6. Modern computing in the era of Integrated Circuits
* 2000s: Appearance of barriers to single-thread computing
* The only solution: parallelism
* Moore's law: sustainable or not?

### 7. Introduction to various offered group projects (A4)
* CPU and MIC (many integrated cores, Xeon Phi)
* art and phi cluster at UTSC
* Supercomputers and supercomputing in 2020s
* Particle disks on an MIC cluster
* More C. Multi-dimensional arrays in C vs. Fortran

### 8. Parallelization via OpenMP in C and F
* Segmentation faults due to limited stack
* Bottlenecks: Computation vs. RAM bandwidth (on CPU)
* Calling C functions from Python
* Graphics in Fortran and C: DISLIN library
* Parallel implementations: diffusion and wave equation
* Linked lists, nearest neighbor search
* Smoothed Particle Hydrodynamics implementation

### 9. Computations with CPU vs. MIC vs. CUDA
* Automatic vectorization and compiler reports
* Optically thick disk calculation (IRI)
* N-body integration methods and implementations
* Basic Neural Net: teaching a broom to stand upside down

### 10. Interaction of protoplanets with 3D particle and gas disks
* Fluids by Eulerian vs. Lagrangian methods: CPU and GPU.
* Incompressible flow algorithm (fluidsGL)
* Fourier integral & discrete transform. FFT, $N \ln N$ scaling.
* Gravitational potential by FFT convolution
* Aliasing and zero-padding
* Examples of simple GPU programs written in CUDA Fortran

### 11. Discussion of assignment A3 solutions
* Simple GPU programs in CUDA C/C++
* CUDA computation of tetrahedrons puzzle & Laplacians
* Introduction to MPI
* What are NNs and why do they work despite the dimensionality curse
* Machine Learning, Artificial Intelligence, Neural Networks
* The overfitting problem [Gershenfeld "The Nature of Mathematical Modeling" (1999)]
* Optimum Search: Simplex (Nelder-Mead) method

### 12. Presentation of your A4 group projects

---

# PHYD57 References & Literature Library

*NOTICE - links do not work on this page. Ask fellow students, then the lecturer why (in that order!).*

### General
* First of all, if you are interested in introductory numerical methods (PSCB57) please see here [this course page](http://planets.utsc.utoronto.ca/~pawel/PSCB57) available for a limited time only.
* Next, page through this book paying attention mainly to the discussion of Python vs C vs Fortran, and any other topics new to you. You should know much of the rest - basic numerical methods, that is:  
  **[Shoerghofer - Lessons in Scientific Computing](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Schoerghofer-Lessons.pdf)**
* For those interested:  
  **[Ceruzzi - History of Modern Computing](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Ceruzzi-History_of_Modern_Computing.pdf)**
* New textbook on Python3:  
  **[Linge - Programming for Computations (Python 3)](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Linge-Programming_for_Computations.pdf)**
* We've used this to learn numerical methods in introductory course PSCB57:  
  **[Turner - Applied Sci Computing w/Python](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Turner-Applied_Sci_Computing_Python-.pdf)**
* Read chapter 2 on Fortran. Also chapter 3 on Python if you forgot it (we also used it in PSCB57 in 2019):  
  **[Izaac - Computational QM](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Izaac-Computational_QM-2019.pdf)**

### Linux (CentOS)
* Links to online materials are on our course page.
* You are encouraged to install Centos OS on your computer but not required to. On art-2 there is an account for you, and you were shown a password to it, if you forgot please ask in person. This system has Centos6 OS available for your exercises. To be able to do anything there, you need to learn basic Linux, and if you're connecting from a Windows system, install an SSH (secure shell) client program PuTTY or similar, on the Windows machine. ssh is the way to connect securely and work on a remote linux server, while sftp is a similar client that connects for the purpose of transferring files between two machines on internet.
* Try this one, it will help you with setting up your own server, or just use it (Chapter 3 Getting Started with CentOS p.45):  
  **[Membrey - Definitive Guide to Centos-2009.pdf](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Membrey-Definit_Guide_to_Centos-2009.pdf)**
* Brief summary of the most important unix/linux commands:  
  **[Gedris - Intro Linux_Command_Shell for Beginners](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Gedris-Intro_Linux_Command_Shell_for_Beginners-2003.pdf)**  
  *(Frankly, web resources are as good as books for mastering software, though it's harder to find the right pages. The Linux Information Project at http://www.linfo.org/ is a good entry point to some.)*
* And this one (the first 5 chapters):  
  **[Matthew - Beginning Linux Programming](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Matthew,Stones-Beginning_Linux_Programming-2008.pdf)**
* Or maybe this one. Yes, this one's good and up to date:  
  **[Sobell - Practical Guide to Linux Commands](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Sobell-A_practical_Guide_to_Linux_Commands-2018.pdf)**

*(In the above books, please skip those sections which deal with: emacs, sed, perl, awk, any SQL databases, semaphores, pipes, sockets, posix...). You do want to know how to use, without trying to know ALL capabilities of, the following: bash and/or tcsh shells, vim, nano, and one other, window-style cursor-driven editor, as well as ssh and sftp.)*

### FORTRAN
*Enjoy learning this language and please remember that writing anything in CAPS in the text of a program is outmoded (at least in the last 25 years :-) so write everything in the style of Python, but be aware that variable Var_One and var_one, as well as Var_one, are one and the same in Fortran.*

* History of FORTRAN:  
  **[Backus - History of Fortran I,II,III.pdf](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Backus-History_of_Fortran_I,II,III.pdf)**
* Here is a good book, though it may have too much detail:  
  **[Chivers - Intro to Prog w Fortran 2018](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Chivers-Intro_to_Prog_w_Fortran-4ed-2018.pdf)**
* Also this one is good:  
  **[Chapman - Fortran for Scientists and Engineers](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Chapman-Fortran_for_Scientists_and_Engineers-2018.pdf)**
* Maybe you prefer this book for learning Fortran?  
  **[Brainerd - Guide to Fortran_2008 Programing](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Brainerd-Guide_to_Fortran_2008_Programing-2015.pdf)**
* A must-read for GPU programming in Fortran, virtually the only one:  
  **[Fatica - CUDA Fortran for Scientists and Engineers](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Fatica,Ruetsch-CUDA_Fortran_for_Sci_and_Eng-2014.pdf)**
* Online:  
  **[CUDA Fortran Programming Guide (Nvidia)](https://docs.nvidia.com/hpc-sdk/compilers/cuda-fortran-prog-guide)**

### C/C++
* The original book by creators of C language - it's a little anachronistic but the pieces of code are worth looking at:  
  **[Kernighan & Ritchie - Ansi_C_Programming](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Kernighan,Ritchie-Ansi_C_Programming.pdf)**
* Not bad:  
  **[Deitel - C. How to Program. Intro to C++](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Deitel-C_How_to_Program.Intro_C++_2016.pdf)**
* Nice:  
  **[Kochan - Programming in C. A Complete Introduction](http://planets.utsc.utoronto.ca/~pawel/PHYD57/Kochan-Programming_in_C.A_Complete_Intro-2004.pdf)**
